# Markdownlint configuration for Aspen project
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length restriction for technical documentation
MD013: false

# Allow inline HTML (useful for technical docs)
MD033: false

# Allow multiple consecutive blank lines (useful for document structure)
MD012: false

# Allow bare URLs (common in technical documentation)
MD034: false

# Allow duplicate headings (common in large planning documents with sections)
MD024: false

# Allow fenced code blocks without language (mixed code types in docs)
MD040: false

# Allow inconsistent ordered list numbering (intentional section numbering)
MD029: false

# Allow emphasis as heading (useful for sub-subsections)
MD036: false
