//! Age key file management.
//!
//! Loads age keys from the manifest's `ageKeyFile` and converts SSH ed25519
//! keys from `ageSshKeyPaths` into age identities. Writes a combined key file
//! that `aspen_secrets::sops::decrypt` can use via the `age_identity` config.

use std::fs;
use std::io::Write;
use std::path::Path;

use anyhow::Context;
use anyhow::Result;
use tracing::info;
use tracing::warn;

use crate::manifest::Manifest;

/// Import age keys from manifest configuration and write a combined key file.
///
/// Returns the path to the combined key file, or `None` if no keys were found.
pub fn import_age_keys(manifest: &Manifest, mount_point: &str, log_imports: bool) -> Result<Option<String>> {
    let has_key_file = manifest.age_key_file.as_ref().is_some_and(|p| !p.is_empty());
    let has_ssh_keys = !manifest.age_ssh_key_paths.is_empty();

    if !has_key_file && !has_ssh_keys {
        return Ok(None);
    }

    let keyfile_path = format!("{mount_point}/age-keys.txt");
    let mut keyfile = fs::File::create(&keyfile_path).with_context(|| format!("cannot create '{keyfile_path}'"))?;

    // Set restrictive permissions
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        fs::set_permissions(&keyfile_path, perms)
            .with_context(|| format!("cannot set permissions on '{keyfile_path}'"))?;
    }

    writeln!(keyfile, "# generated by sops-install-secrets at {}", chrono_now_rfc3339())?;

    // Import SSH ed25519 keys as age identities
    if has_ssh_keys {
        import_ssh_keys(&manifest.age_ssh_key_paths, &mut keyfile, log_imports);
    }

    // Append the age key file contents
    if let Some(ref age_key_path) = manifest.age_key_file
        && !age_key_path.is_empty()
    {
        match fs::read_to_string(age_key_path) {
            Ok(contents) => {
                writeln!(keyfile, "{contents}")?;
                if log_imports {
                    info!("Imported age key file: {age_key_path}");
                }
            }
            Err(e) => {
                warn!("Cannot read age key file '{age_key_path}': {e}");
            }
        }
    }

    // Set env var for SOPS decrypt
    // SAFETY: This runs early in main, before any other threads are spawned.
    unsafe { std::env::set_var("SOPS_AGE_KEY_FILE", &keyfile_path) };

    Ok(Some(keyfile_path))
}

/// Convert SSH ed25519 private keys to age identities.
fn import_ssh_keys(paths: &[String], keyfile: &mut fs::File, log_imports: bool) {
    for path in paths {
        match convert_ssh_to_age(Path::new(path)) {
            Ok((private_key, public_key)) => {
                if let Err(e) = writeln!(keyfile, "{private_key}") {
                    warn!("Cannot write key to age file: {e}");
                    continue;
                }
                if log_imports {
                    eprintln!("sops-install-secrets: Imported {path} as age key with fingerprint {public_key}");
                }
            }
            Err(e) => {
                warn!("Cannot convert SSH key '{path}': {e}");
            }
        }
    }
}

/// Convert an SSH ed25519 private key file to age identity + public key strings.
///
/// Returns `(age_secret_key, age_public_key)`.
fn convert_ssh_to_age(path: &Path) -> Result<(String, String)> {
    let pem = fs::read_to_string(path).with_context(|| format!("cannot read SSH key '{}'", path.display()))?;

    let private_key = ssh_key::PrivateKey::from_openssh(&pem)
        .with_context(|| format!("cannot parse SSH key '{}'", path.display()))?;

    match private_key.key_data() {
        ssh_key::private::KeypairData::Ed25519(kp) => {
            // The age identity is derived from the ed25519 seed (first 32 bytes of private key)
            // ssh-to-age uses the same conversion as age's SSH key support
            // Ed25519 seed → X25519 scalar via SHA-512 + clamping.
            // This matches the ssh-to-age algorithm used by sops-nix's Go code.
            let seed = kp.private.to_bytes();
            let x25519_scalar = ed25519_seed_to_x25519_scalar(&seed);

            // Bech32-encode as AGE-SECRET-KEY-1...
            let secret_key_str = encode_age_secret_key(&x25519_scalar)?;

            // Parse back through age to get the public key for logging
            let identity: age::x25519::Identity = secret_key_str
                .parse()
                .map_err(|e| anyhow::anyhow!("internal error: generated invalid age key: {e}"))?;
            let public_key = identity.to_public().to_string();

            Ok((secret_key_str, public_key))
        }
        _ => {
            anyhow::bail!("SSH key '{}' is not ed25519 (type: {:?}), skipping", path.display(), private_key.algorithm())
        }
    }
}

/// Convert an ed25519 seed to an X25519 scalar.
///
/// This is the standard ed25519→X25519 conversion (RFC 8032 / libsodium):
/// 1. SHA-512 the seed
/// 2. Take the first 32 bytes
/// 3. Clamp: clear bits 0,1,2 of first byte; clear bit 7, set bit 6 of last byte
fn ed25519_seed_to_x25519_scalar(seed: &[u8; 32]) -> [u8; 32] {
    use sha2::Digest;
    let hash = sha2::Sha512::digest(seed);
    let mut scalar = [0u8; 32];
    scalar.copy_from_slice(&hash[..32]);
    // Clamp
    scalar[0] &= 248;
    scalar[31] &= 127;
    scalar[31] |= 64;
    scalar
}

/// Bech32-lower encode a 32-byte X25519 scalar as an AGE-SECRET-KEY-1... string.
fn encode_age_secret_key(scalar: &[u8; 32]) -> Result<String> {
    let hrp = bech32::Hrp::parse("age-secret-key-").map_err(|e| anyhow::anyhow!("bech32 hrp error: {e}"))?;
    let encoded =
        bech32::encode::<bech32::Bech32>(hrp, scalar).map_err(|e| anyhow::anyhow!("bech32 encode error: {e}"))?;
    Ok(encoded.to_uppercase())
}

/// Get current time as RFC 3339 string without pulling in chrono.
fn chrono_now_rfc3339() -> String {
    // Use std::time for a simple timestamp
    use std::time::SystemTime;
    let now = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default();
    format!("{}", now.as_secs())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn convert_non_ed25519_fails() {
        // Create a temp file with an RSA key header (will fail to parse as ed25519)
        let dir = tempfile::tempdir().unwrap();
        let key_path = dir.path().join("rsa_key");
        // Write a minimal invalid key — just enough to test the error path
        fs::write(&key_path, "not a valid ssh key").unwrap();

        let result = convert_ssh_to_age(&key_path);
        assert!(result.is_err());
    }

    #[test]
    fn convert_missing_file_fails() {
        let result = convert_ssh_to_age(Path::new("/nonexistent/key"));
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("cannot read"));
    }
}
