//! sops-nix manifest JSON types.
//!
//! These structs match the Go `sops-install-secrets` manifest format exactly.
//! The manifest is generated by Nix at build time (`manifest-for.nix`) and
//! consumed by this binary at NixOS activation time.

use serde::Deserialize;

/// Top-level manifest produced by sops-nix.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Manifest {
    /// Secrets to decrypt and install.
    pub secrets: Vec<SecretEntry>,

    /// Templates to render with decrypted secret values.
    #[serde(default)]
    pub templates: Vec<TemplateEntry>,

    /// Map of secret name → placeholder string used in templates.
    #[serde(default)]
    pub placeholder_by_secret_name: std::collections::HashMap<String, String>,

    /// Mount point for the secrets ramfs/tmpfs (e.g., `/run/secrets.d`).
    pub secrets_mount_point: String,

    /// Symlink path pointing to the current generation (e.g., `/run/secrets`).
    pub symlink_path: String,

    /// Number of old generations to keep. 0 = no pruning.
    pub keep_generations: u32,

    /// GPG SSH key paths (for GPG key import — not supported, ignored).
    #[serde(default)]
    pub ssh_key_paths: Vec<String>,

    /// GnuPG home directory (not supported, ignored).
    #[serde(default)]
    pub gnupg_home: Option<String>,

    /// Path to age key file.
    #[serde(default)]
    pub age_key_file: Option<String>,

    /// SSH key paths to convert to age identities.
    #[serde(default)]
    pub age_ssh_key_paths: Vec<String>,

    /// Use tmpfs instead of ramfs.
    #[serde(default)]
    pub use_tmpfs: bool,

    /// User-mode operation (non-root). Not supported in initial version.
    #[serde(default)]
    pub user_mode: bool,

    /// Logging configuration.
    #[serde(default)]
    pub logging: LoggingConfig,
}

/// A secret entry in the manifest.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SecretEntry {
    /// Secret name (used as filename under the generation directory).
    pub name: String,

    /// Key path within the decrypted SOPS file (e.g., `database/password`).
    /// Empty string means use the entire file.
    #[serde(default)]
    pub key: String,

    /// Symlink path for the secret (e.g., `/run/secrets/db-password`).
    pub path: String,

    /// Owner username. Mutually exclusive with `uid`.
    #[serde(default)]
    pub owner: Option<String>,

    /// Owner UID (used when `owner` is null).
    #[serde(default)]
    pub uid: u32,

    /// Group name. Mutually exclusive with `gid`.
    #[serde(default)]
    pub group: Option<String>,

    /// Group GID (used when `group` is null).
    #[serde(default)]
    pub gid: u32,

    /// Path to the SOPS-encrypted file.
    pub sops_file: String,

    /// File format.
    pub format: FormatType,

    /// File mode as octal string (e.g., "0400").
    #[serde(default = "default_mode")]
    pub mode: String,

    /// systemd units to restart when this secret changes.
    #[serde(default)]
    pub restart_units: Vec<String>,

    /// systemd units to reload when this secret changes.
    #[serde(default)]
    pub reload_units: Vec<String>,
}

/// A template entry in the manifest.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TemplateEntry {
    /// Template name (used as filename under `rendered/`).
    pub name: String,

    /// Inline template content. Mutually exclusive with `file`.
    #[serde(default)]
    pub content: String,

    /// Path to template file. Mutually exclusive with `content`.
    #[serde(default)]
    pub file: String,

    /// Output path for the rendered template.
    pub path: String,

    /// File mode as octal string.
    #[serde(default = "default_mode")]
    pub mode: String,

    /// Owner username.
    #[serde(default)]
    pub owner: Option<String>,

    /// Owner UID.
    #[serde(default)]
    pub uid: u32,

    /// Group name.
    #[serde(default)]
    pub group: Option<String>,

    /// Group GID.
    #[serde(default)]
    pub gid: u32,

    /// Template source file path (sops-nix >= 0.1).
    #[serde(default)]
    pub restart_units: Vec<String>,

    /// systemd units to reload when this template changes.
    #[serde(default)]
    pub reload_units: Vec<String>,
}

/// Supported SOPS file formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FormatType {
    Yaml,
    Json,
    Binary,
    Dotenv,
    Ini,
}

impl FormatType {
    /// Check if this format is supported by aspen-sops.
    pub fn is_supported(self) -> bool {
        matches!(self, FormatType::Yaml | FormatType::Json | FormatType::Binary)
    }
}

impl std::fmt::Display for FormatType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FormatType::Yaml => write!(f, "yaml"),
            FormatType::Json => write!(f, "json"),
            FormatType::Binary => write!(f, "binary"),
            FormatType::Dotenv => write!(f, "dotenv"),
            FormatType::Ini => write!(f, "ini"),
        }
    }
}

/// Logging configuration.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoggingConfig {
    /// Log key import events.
    #[serde(default)]
    pub key_import: bool,

    /// Log secret change summaries.
    #[serde(default)]
    pub secret_changes: bool,
}

impl Default for LoggingConfig {
    fn default() -> Self {
        Self {
            key_import: true,
            secret_changes: true,
        }
    }
}

fn default_mode() -> String {
    "0400".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Sample manifest JSON matching what sops-nix generates.
    fn sample_manifest_json() -> &'static str {
        r#"{
            "secrets": [
                {
                    "name": "db-password",
                    "key": "database/password",
                    "path": "/run/secrets/db-password",
                    "owner": "root",
                    "uid": 0,
                    "group": "root",
                    "gid": 0,
                    "sopsFile": "/nix/store/abc-secrets.yaml",
                    "format": "yaml",
                    "mode": "0400",
                    "restartUnits": ["myapp.service"],
                    "reloadUnits": []
                },
                {
                    "name": "api-key",
                    "key": "api/key",
                    "path": "/run/secrets/api-key",
                    "uid": 1000,
                    "gid": 1000,
                    "sopsFile": "/nix/store/abc-secrets.yaml",
                    "format": "yaml",
                    "mode": "0440",
                    "restartUnits": [],
                    "reloadUnits": []
                }
            ],
            "templates": [
                {
                    "name": "app-config",
                    "content": "db_pass=<<PLACEHOLDER_db-password>>",
                    "file": "",
                    "path": "/run/secrets/rendered/app-config",
                    "mode": "0440",
                    "uid": 0,
                    "gid": 0,
                    "restartUnits": [],
                    "reloadUnits": []
                }
            ],
            "placeholderBySecretName": {
                "db-password": "<<PLACEHOLDER_db-password>>",
                "api-key": "<<PLACEHOLDER_api-key>>"
            },
            "secretsMountPoint": "/run/secrets.d",
            "symlinkPath": "/run/secrets",
            "keepGenerations": 1,
            "sshKeyPaths": [],
            "gnupgHome": "",
            "ageKeyFile": "/var/lib/sops-nix/key.txt",
            "ageSshKeyPaths": ["/etc/ssh/ssh_host_ed25519_key"],
            "useTmpfs": false,
            "userMode": false,
            "logging": {
                "keyImport": true,
                "secretChanges": true
            }
        }"#
    }

    #[test]
    fn parse_sample_manifest() {
        let manifest: Manifest = serde_json::from_str(sample_manifest_json()).unwrap();

        assert_eq!(manifest.secrets.len(), 2);
        assert_eq!(manifest.secrets[0].name, "db-password");
        assert_eq!(manifest.secrets[0].key, "database/password");
        assert_eq!(manifest.secrets[0].sops_file, "/nix/store/abc-secrets.yaml");
        assert_eq!(manifest.secrets[0].format, FormatType::Yaml);
        assert_eq!(manifest.secrets[0].mode, "0400");
        assert_eq!(manifest.secrets[0].owner, Some("root".to_string()));
        assert_eq!(manifest.secrets[0].restart_units, vec!["myapp.service"]);

        assert_eq!(manifest.secrets[1].name, "api-key");
        assert_eq!(manifest.secrets[1].owner, None);
        assert_eq!(manifest.secrets[1].uid, 1000);
        assert_eq!(manifest.secrets[1].gid, 1000);

        assert_eq!(manifest.templates.len(), 1);
        assert_eq!(manifest.templates[0].name, "app-config");
        assert!(manifest.templates[0].content.contains("PLACEHOLDER"));

        assert_eq!(manifest.placeholder_by_secret_name.len(), 2);
        assert_eq!(manifest.secrets_mount_point, "/run/secrets.d");
        assert_eq!(manifest.symlink_path, "/run/secrets");
        assert_eq!(manifest.keep_generations, 1);
        assert_eq!(manifest.age_key_file, Some("/var/lib/sops-nix/key.txt".to_string()));
        assert_eq!(manifest.age_ssh_key_paths, vec!["/etc/ssh/ssh_host_ed25519_key"]);
        assert!(!manifest.use_tmpfs);
        assert!(!manifest.user_mode);
        assert!(manifest.logging.key_import);
        assert!(manifest.logging.secret_changes);
    }

    #[test]
    fn parse_minimal_manifest() {
        let json = r#"{
            "secrets": [],
            "secretsMountPoint": "/run/secrets.d",
            "symlinkPath": "/run/secrets",
            "keepGenerations": 1
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(manifest.secrets.is_empty());
        assert!(manifest.templates.is_empty());
        assert!(manifest.age_key_file.is_none());
    }

    #[test]
    fn parse_unknown_fields_tolerated() {
        let json = r#"{
            "secrets": [],
            "secretsMountPoint": "/run/secrets.d",
            "symlinkPath": "/run/secrets",
            "keepGenerations": 1,
            "futureField": "some-value",
            "anotherFutureField": 42
        }"#;
        // Should not panic — unknown fields are ignored
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(manifest.secrets.is_empty());
    }

    #[test]
    fn format_type_supported() {
        assert!(FormatType::Yaml.is_supported());
        assert!(FormatType::Json.is_supported());
        assert!(FormatType::Binary.is_supported());
        assert!(!FormatType::Dotenv.is_supported());
        assert!(!FormatType::Ini.is_supported());
    }

    #[test]
    fn format_type_display() {
        assert_eq!(FormatType::Yaml.to_string(), "yaml");
        assert_eq!(FormatType::Json.to_string(), "json");
        assert_eq!(FormatType::Binary.to_string(), "binary");
        assert_eq!(FormatType::Dotenv.to_string(), "dotenv");
        assert_eq!(FormatType::Ini.to_string(), "ini");
    }
}
