#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum DagSyncIssue {
    InvalidBounds,
    EmptyRoots,
    TooManyRoots,
    TooManyNodes,
    TooManyEdges,
    TooManyPeers,
    ByteBoundExceeded,
    StepBoundExceeded,
    DepthBoundExceeded,
    DuplicateRoot,
    DuplicateNode,
    DuplicateEdge,
    DuplicateInventoryObject,
    UnknownRoot,
    UnknownEdgeTarget,
    Cycle,
    InvalidDomain,
    InvalidNodeLength,
    ProgressEpochMismatch,
    ProgressGenerationMismatch,
    ProgressStrategyMismatch,
    ProgressPolicyMismatch,
    ProgressRootMismatch,
    ProgressSchemaMismatch,
    ProgressPeerAssignmentMismatch,
    ProgressStepRegression,
    ProgressContainsUnknownObject,
    StrategyRequiresPeers,
    UnsolicitedResponse,
    DuplicateResponse,
    ResponseEpochMismatch,
    ResponseGenerationMismatch,
    ResponsePeerMismatch,
    ResponseIdentityMismatch,
    ResponseUnauthorized,
    ResponseByteMismatch,
    TransferDeferred,
    TransferCancelled,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DagPlanResult {
    pub plan: Option<super::DagSyncPlan>,
    pub issues: Vec<DagSyncIssue>,
}

impl DagSyncIssue {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InvalidBounds => "invalid-bounds",
            Self::EmptyRoots => "empty-roots",
            Self::TooManyRoots => "too-many-roots",
            Self::TooManyNodes => "too-many-nodes",
            Self::TooManyEdges => "too-many-edges",
            Self::TooManyPeers => "too-many-peers",
            Self::ByteBoundExceeded => "byte-bound-exceeded",
            Self::StepBoundExceeded => "step-bound-exceeded",
            Self::DepthBoundExceeded => "depth-bound-exceeded",
            Self::DuplicateRoot => "duplicate-root",
            Self::DuplicateNode => "duplicate-node",
            Self::DuplicateEdge => "duplicate-edge",
            Self::DuplicateInventoryObject => "duplicate-inventory-object",
            Self::UnknownRoot => "unknown-root",
            Self::UnknownEdgeTarget => "unknown-edge-target",
            Self::Cycle => "cycle",
            Self::InvalidDomain => "invalid-domain",
            Self::InvalidNodeLength => "invalid-node-length",
            Self::ProgressEpochMismatch => "progress-epoch-mismatch",
            Self::ProgressGenerationMismatch => "progress-generation-mismatch",
            Self::ProgressStrategyMismatch => "progress-strategy-mismatch",
            Self::ProgressPolicyMismatch => "progress-policy-mismatch",
            Self::ProgressRootMismatch => "progress-root-mismatch",
            Self::ProgressSchemaMismatch => "progress-schema-mismatch",
            Self::ProgressPeerAssignmentMismatch => "progress-peer-assignment-mismatch",
            Self::ProgressStepRegression => "progress-step-regression",
            Self::ProgressContainsUnknownObject => "progress-contains-unknown-object",
            Self::StrategyRequiresPeers => "strategy-requires-peers",
            Self::UnsolicitedResponse => "unsolicited-response",
            Self::DuplicateResponse => "duplicate-response",
            Self::ResponseEpochMismatch => "response-epoch-mismatch",
            Self::ResponseGenerationMismatch => "response-generation-mismatch",
            Self::ResponsePeerMismatch => "response-peer-mismatch",
            Self::ResponseIdentityMismatch => "response-identity-mismatch",
            Self::ResponseUnauthorized => "response-unauthorized",
            Self::ResponseByteMismatch => "response-byte-mismatch",
            Self::TransferDeferred => "transfer-deferred",
            Self::TransferCancelled => "transfer-cancelled",
        }
    }
}
