include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p000/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p001/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p002/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p003/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p004/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p005/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p006/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p007/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/protocol/parts/session/p008/body.rs"));
