//! Domain-specific request handlers for Client RPC.

// Handler modules
#[cfg(feature = "automerge")]
pub mod automerge;
#[cfg(feature = "blob")]
pub mod blob;
#[cfg(feature = "ci")]
pub mod ci;
pub mod cluster;
pub mod coordination;
pub mod core;
#[cfg(feature = "dns")]
pub mod dns;
pub mod docs;
#[cfg(feature = "forge")]
pub mod forge;
pub mod hooks;
pub mod job;
pub mod kv;
pub mod lease;
#[cfg(feature = "pijul")]
pub mod pijul;
#[cfg(feature = "secrets")]
pub mod secrets;
pub mod service_registry;
#[cfg(feature = "sql")]
pub mod sql;
pub mod watch;

// Re-export handlers
pub use core::CoreHandler;

#[cfg(feature = "automerge")]
pub use automerge::AutomergeHandler;
#[cfg(feature = "blob")]
pub use blob::BlobHandler;
#[cfg(feature = "ci")]
pub use ci::CiHandler;
pub use cluster::ClusterHandler;
pub use coordination::CoordinationHandler;
#[cfg(feature = "dns")]
pub use dns::DnsHandler;
pub use docs::DocsHandler;
#[cfg(feature = "forge")]
pub use forge::ForgeHandler;
pub use hooks::HooksHandler;
pub use job::JobHandler;
pub use kv::KvHandler;
pub use lease::LeaseHandler;
#[cfg(feature = "pijul")]
pub use pijul::PijulHandler;
#[cfg(feature = "secrets")]
pub use secrets::SecretsHandler;
#[cfg(feature = "secrets")]
pub use secrets::SecretsService;
pub use service_registry::ServiceRegistryHandler;
#[cfg(feature = "sql")]
pub use sql::SqlHandler;
pub use watch::WatchHandler;
