use serde::Deserialize;
use serde::Serialize;

use super::*;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "kebab-case", deny_unknown_fields)]
pub enum ActorIssue {
    SchemaMismatch,
    UnsupportedProfileVersion,
    ReferenceSourceMismatch,
    MalformedActorKey,
    MalformedReference,
    MalformedOperationId,
    InvalidIdlePolicy,
    IdleThresholdNotReached,
    InvalidDrainPolicy,
    SurvivalMatrixMismatch,
    DuplicateSurvivalClass,
    MissingNonClaim,
    ProfileIdentityMismatch,
    StateIdentityMismatch,
    StaleActorKey,
    StalePlacement,
    StaleGeneration,
    StaleLifecycleSequence,
    AdmissionDenied,
    UnknownExternalOutcome,
    IllegalPhase { phase: ActorPhase, operation: String },
    ActiveWake,
    WakeMismatch,
    PendingMailboxItems,
    UnresolvedEffects,
    DrainNotComplete,
    RestoreClassDenied { class: SurvivalClass },
    DuplicateRestoreClass { class: SurvivalClass },
    OperationCapacityExceeded,
    CompletedEventCapacityExceeded,
    CounterOverflow,
    MissingCheckpoint,
    UnknownEffectMismatch,
    DeliveryCommitRequired,
    SystemExtensionPhaseMismatch,
    SystemExtensionGenerationMismatch,
    SystemExtensionCheckpointMismatch,
}

impl ActorIssue {
    pub const fn code(&self) -> &'static str {
        match self {
            Self::SchemaMismatch => "schema-mismatch",
            Self::UnsupportedProfileVersion => "unsupported-profile-version",
            Self::ReferenceSourceMismatch => "reference-source-mismatch",
            Self::MalformedActorKey => "malformed-actor-key",
            Self::MalformedReference => "malformed-reference",
            Self::MalformedOperationId => "malformed-operation-id",
            Self::InvalidIdlePolicy => "invalid-idle-policy",
            Self::IdleThresholdNotReached => "idle-threshold-not-reached",
            Self::InvalidDrainPolicy => "invalid-drain-policy",
            Self::SurvivalMatrixMismatch => "survival-matrix-mismatch",
            Self::DuplicateSurvivalClass => "duplicate-survival-class",
            Self::MissingNonClaim => "missing-non-claim",
            Self::ProfileIdentityMismatch => "profile-identity-mismatch",
            Self::StateIdentityMismatch => "state-identity-mismatch",
            Self::StaleActorKey => "stale-actor-key",
            Self::StalePlacement => "stale-placement",
            Self::StaleGeneration => "stale-generation",
            Self::StaleLifecycleSequence => "stale-lifecycle-sequence",
            Self::AdmissionDenied => "admission-denied",
            Self::UnknownExternalOutcome => "unknown-external-outcome",
            Self::IllegalPhase { .. } => "illegal-phase",
            Self::ActiveWake => "active-wake",
            Self::WakeMismatch => "wake-mismatch",
            Self::PendingMailboxItems => "pending-mailbox-items",
            Self::UnresolvedEffects => "unresolved-effects",
            Self::DrainNotComplete => "drain-not-complete",
            Self::RestoreClassDenied { .. } => "restore-class-denied",
            Self::DuplicateRestoreClass { .. } => "duplicate-restore-class",
            Self::OperationCapacityExceeded => "operation-capacity-exceeded",
            Self::CompletedEventCapacityExceeded => "completed-event-capacity-exceeded",
            Self::CounterOverflow => "counter-overflow",
            Self::MissingCheckpoint => "missing-checkpoint",
            Self::UnknownEffectMismatch => "unknown-effect-mismatch",
            Self::DeliveryCommitRequired => "delivery-commit-required",
            Self::SystemExtensionPhaseMismatch => "system-extension-phase-mismatch",
            Self::SystemExtensionGenerationMismatch => "system-extension-generation-mismatch",
            Self::SystemExtensionCheckpointMismatch => "system-extension-checkpoint-mismatch",
        }
    }
}
