use super::CompatibilityStatus;
use super::OracleNonClaim;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum OracleIssue {
    SchemaMismatch,
    SourceMismatch,
    AdapterMismatch,
    BackendFormatMismatch,
    RemoteSupportEnabled,
    Vec1Unexpected,
    ImportedScopeMismatch,
    BuildInputMismatch,
    NoticeMismatch,
    ContractMismatch,
    MalformedReference(String),
    InvalidBounds,
    DuplicateCompatibilityRow(String),
    CompatibilityEvidenceMissing(String),
    CompatibilityFixtureMissing(String),
    CompatibilityExplanationMissing(String),
    CompatibilityIssueMissing(String),
    CompatibilityLimitExceeded(CompatibilityStatus),
    RowLimitExceeded,
    DuplicateSemanticKey(String),
    NonCanonicalRowOrder,
    KeyLimitExceeded(String),
    ValueLimitExceeded(String),
    DiagnosticLimitExceeded,
    ObservationIdentityMismatch,
    BackendIdentityOverclaim,
    MissingNonClaim(OracleNonClaim),
    ComparisonCaseMismatch,
    ComparisonIdentityMismatch,
    ComparisonOverclaim,
    ProjectionComparisonMismatch,
    ProjectionIdentityMismatch,
    ProjectionOverclaim,
}
