[workspace]
resolver = "3"
members = ["."]

[workspace.metadata.octet]
default_scope = ["--workspace"]
cargo_check_args = ["--all-targets", "--all-features"]

[package]
name = "molten-prolly-map-octet"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
blake3 = "=1.8.5"
content-identity-core = { git = "https://seed.radicle.garden/zA14jhTdwST4PxPBdsryc4zS7Kpq.git", rev = "7f55597b5dc879b7601856e8d7fd0dbacaa2a498", version = "0.1.0" }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
