use std::env;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;
use std::process::Output;

const CARGO_BINARY: &str = "cargo";
const CHECK_SUBCOMMAND: &str = "check";
const COLOR_FLAG: &str = "--color";
const COLOR_NEVER: &str = "never";
const QUIET_FLAG: &str = "--quiet";
const MANIFEST_FLAG: &str = "--manifest-path";
const UI_TARGET_DIR_RELATIVE: &str = "target/ui-fixtures";
const EVIDENCE_DIR_RELATIVE: &str = "openspec/changes/no-std-aspen-core/evidence";
const FIXTURE_INDEX_FILE_NAME: &str = "ui-fixtures.txt";
const STDERR_FILE_PREFIX: &str = "ui-";
const STDERR_FILE_SUFFIX: &str = ".stderr";
const NORMALIZED_REPO_ROOT: &str = "$REPO_ROOT";
const LINE_SEPARATOR: &str = "\n";
const MISSING_SNAPSHOT_HINT: &str = "missing stderr snapshot; re-run after writing generated snapshot";

#[derive(Clone, Copy, Debug)]
struct UiFixture {
    name: &'static str,
    manifest_relative_path: &'static str,
    feature_settings: &'static str,
    expected_stderr_substrings: &'static [&'static str],
}

const APP_REGISTRY_EXPECTED: &[&str] = &["no `AppRegistry` in the root"];
const NETWORK_TRANSPORT_EXPECTED: &[&str] = &["no `NetworkTransport` in the root"];
const SIMULATION_ARTIFACT_EXPECTED: &[&str] = &["no `SimulationArtifact` in the root"];
const CONTENT_DISCOVERY_EXPECTED: &[&str] = &["no `ContentDiscovery` in the root"];
const DIRECTORY_LAYER_EXPECTED: &[&str] = &["no `DirectoryLayer` in the root"];

const UI_FIXTURES: &[UiFixture] = &[
    UiFixture {
        name: "app-registry-no-std",
        manifest_relative_path: "crates/aspen-core/tests/ui/app-registry-no-std/Cargo.toml",
        feature_settings: "default-features = false",
        expected_stderr_substrings: APP_REGISTRY_EXPECTED,
    },
    UiFixture {
        name: "network-transport-no-std",
        manifest_relative_path: "crates/aspen-core/tests/ui/network-transport-no-std/Cargo.toml",
        feature_settings: "default-features = false",
        expected_stderr_substrings: NETWORK_TRANSPORT_EXPECTED,
    },
    UiFixture {
        name: "simulation-artifact-no-std",
        manifest_relative_path: "crates/aspen-core/tests/ui/simulation-artifact-no-std/Cargo.toml",
        feature_settings: "default-features = false",
        expected_stderr_substrings: SIMULATION_ARTIFACT_EXPECTED,
    },
    UiFixture {
        name: "content-discovery-std-without-global-discovery",
        manifest_relative_path: "crates/aspen-core/tests/ui/content-discovery-std-without-global-discovery/Cargo.toml",
        feature_settings: "features = [\"std\"]",
        expected_stderr_substrings: CONTENT_DISCOVERY_EXPECTED,
    },
    UiFixture {
        name: "directory-layer-std-without-layer",
        manifest_relative_path: "crates/aspen-core/tests/ui/directory-layer-std-without-layer/Cargo.toml",
        feature_settings: "features = [\"std\"]",
        expected_stderr_substrings: DIRECTORY_LAYER_EXPECTED,
    },
];

fn repo_root_dir() -> PathBuf {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate dir should live under repo root")
        .to_path_buf()
}

fn evidence_dir(repo_root_dir: &Path) -> PathBuf {
    repo_root_dir.join(EVIDENCE_DIR_RELATIVE)
}

fn target_dir(repo_root_dir: &Path) -> PathBuf {
    repo_root_dir.join(UI_TARGET_DIR_RELATIVE)
}

fn stderr_snapshot_path(repo_root_dir: &Path, fixture: UiFixture) -> PathBuf {
    evidence_dir(repo_root_dir).join(format!("{STDERR_FILE_PREFIX}{}{STDERR_FILE_SUFFIX}", fixture.name))
}

fn fixture_command_string(fixture: UiFixture) -> String {
    format!("{CARGO_BINARY} {CHECK_SUBCOMMAND} {MANIFEST_FLAG} {} {COLOR_FLAG} {COLOR_NEVER} {QUIET_FLAG}", fixture.manifest_relative_path)
}

fn fixture_index_lines() -> Vec<String> {
    let mut lines = vec![
        "# Aspen Core UI fixture index".to_string(),
        String::new(),
        "Generated by `cargo test -p aspen-core --test ui`.".to_string(),
        String::new(),
    ];
    for fixture in UI_FIXTURES {
        lines.push(format!("- fixture: {}", fixture.name));
        lines.push(format!("  manifest: {}", fixture.manifest_relative_path));
        lines.push(format!("  feature-settings: {}", fixture.feature_settings));
        lines.push(format!("  command: {}", fixture_command_string(*fixture)));
    }
    lines.push(String::new());
    lines
}

fn normalize_stderr(raw_stderr: &[u8], repo_root_dir: &Path) -> String {
    let stderr_text = String::from_utf8_lossy(raw_stderr).replace("\r\n", LINE_SEPARATOR);
    let normalized_repo_root = repo_root_dir.to_string_lossy().replace('\\', "/");
    let mut normalized_lines: Vec<String> = Vec::new();
    for raw_line in stderr_text.lines() {
        let replaced_line = raw_line.replace(&normalized_repo_root, NORMALIZED_REPO_ROOT);
        normalized_lines.push(replaced_line.trim_end().to_string());
    }
    let normalized = normalized_lines.join(LINE_SEPARATOR);
    if normalized.ends_with(LINE_SEPARATOR) {
        normalized
    } else {
        format!("{normalized}{LINE_SEPARATOR}")
    }
}

fn run_fixture(repo_root_dir: &Path, fixture: UiFixture) -> Output {
    let manifest_path = repo_root_dir.join(fixture.manifest_relative_path);
    Command::new(CARGO_BINARY)
        .current_dir(repo_root_dir)
        .env("CARGO_TARGET_DIR", target_dir(repo_root_dir))
        .arg(CHECK_SUBCOMMAND)
        .arg(MANIFEST_FLAG)
        .arg(manifest_path)
        .arg(COLOR_FLAG)
        .arg(COLOR_NEVER)
        .arg(QUIET_FLAG)
        .output()
        .expect("cargo check fixture should run")
}

fn write_fixture_index(repo_root_dir: &Path) {
    let fixture_index_path = evidence_dir(repo_root_dir).join(FIXTURE_INDEX_FILE_NAME);
    fs::create_dir_all(evidence_dir(repo_root_dir)).expect("evidence dir should exist");
    fs::write(fixture_index_path, fixture_index_lines().join(LINE_SEPARATOR)).expect("fixture index should write");
}

fn snapshot_exists_and_matches(repo_root_dir: &Path, fixture: UiFixture, normalized_stderr: &str) -> bool {
    let snapshot_path = stderr_snapshot_path(repo_root_dir, fixture);
    if !snapshot_path.exists() {
        fs::write(&snapshot_path, normalized_stderr).expect("missing snapshot should be written");
        return false;
    }
    let expected_stderr = fs::read_to_string(&snapshot_path).expect("stderr snapshot should read");
    assert_eq!(
        expected_stderr,
        normalized_stderr,
        "stderr snapshot mismatch for fixture {} at {}",
        fixture.name,
        snapshot_path.display()
    );
    true
}

#[test]
fn ui_fixtures_fail_for_missing_feature_gates() {
    let repo_root_dir = repo_root_dir();
    let mut missing_snapshots: Vec<&str> = Vec::new();
    write_fixture_index(&repo_root_dir);

    for fixture in UI_FIXTURES {
        println!("fixture {} => {}", fixture.name, fixture_command_string(*fixture));
        let output = run_fixture(&repo_root_dir, *fixture);
        assert!(
            !output.status.success(),
            "fixture {} unexpectedly compiled successfully",
            fixture.name
        );
        let normalized_stderr = normalize_stderr(&output.stderr, &repo_root_dir);
        for expected_substring in fixture.expected_stderr_substrings {
            assert!(
                normalized_stderr.contains(expected_substring),
                "fixture {} stderr missing expected substring `{}`\n{}",
                fixture.name,
                expected_substring,
                normalized_stderr
            );
        }
        if !snapshot_exists_and_matches(&repo_root_dir, *fixture, &normalized_stderr) {
            missing_snapshots.push(fixture.name);
        }
    }

    assert!(
        missing_snapshots.is_empty(),
        "{}: {}",
        MISSING_SNAPSHOT_HINT,
        missing_snapshots.join(", ")
    );
}
