mod comparison;
mod evidence;
mod materialization;
mod model;
mod optimization;
mod profile;
mod runner;

pub use comparison::BenchmarkRunInput;
pub use comparison::benchmark_comparison_ref;
pub use comparison::benchmark_run_ref;
pub use comparison::build_benchmark_run;
pub use comparison::compare_benchmark_runs;
pub use comparison::validate_benchmark_run;
pub use comparison::validate_suite_instance;
pub use evidence::PERFORMANCE_RECEIPT_SCHEMA;
pub use evidence::PerformanceReceipt;
pub use evidence::PerformanceReceiptInput;
pub use evidence::build_performance_receipt;
pub use evidence::performance_receipt_summary;
pub use evidence::performance_receipt_value;
pub use evidence::validate_performance_receipt;
pub use evidence::validate_performance_receipt_against;
pub use materialization::AdmittedPrecompiledComponent;
pub use materialization::PERFORMANCE_MANTLE_BUNDLE_SCHEMA;
pub use materialization::PRECOMPILED_ADMISSION_SCHEMA;
pub use materialization::PerformanceMaterializationBundle;
pub use materialization::PrecompiledComponentManifest;
pub use materialization::PrecompiledRuntimeExpectation;
pub use materialization::WIZER_ADMISSION_SCHEMA;
pub use materialization::WizerTransformManifest;
pub use materialization::WizerVirtualImport;
pub use materialization::admit_precompiled_component;
pub use materialization::admit_wizer_artifact;
pub use materialization::performance_materialization_bundle_ref;
pub use materialization::verify_performance_materialization;
pub use model::BenchmarkComparison;
pub use model::BenchmarkHostFacts;
pub use model::BenchmarkLane;
pub use model::BenchmarkRun;
pub use model::BenchmarkSuite;
pub use model::CapacityDecision;
pub use model::ComparisonDecision;
pub use model::CompilationStrategy;
pub use model::MaterializedPerformanceArtifact;
pub use model::OptimizationProfile;
pub use model::PerformanceArtifactKind;
pub use model::PerformanceDenial;
pub use model::PerformanceEvidenceRole;
pub use model::PerformancePhase;
pub use model::PerformanceProfile;
pub use model::PerformanceResult;
pub use model::PerformanceSample;
pub use model::PhaseComparison;
pub use model::PhaseSamples;
pub use model::RegressionClass;
pub use optimization::BASELINE_OPTIMIZATION_PROFILE_ID;
pub use optimization::COW_OPTIMIZATION_PROFILE_ID;
pub use optimization::INSTANCE_PRE_OPTIMIZATION_PROFILE_ID;
pub use optimization::OptimizationConformanceRecord;
pub use optimization::POOLING_OPTIMIZATION_PROFILE_ID;
pub use optimization::admit_capacity;
pub use optimization::optimization_configuration_ref;
pub use optimization::optimization_conformance_record_ref;
pub use optimization::optimization_profile_ref;
pub use optimization::validate_optimization_conformance;
pub use optimization::validate_optimization_profile;
pub use profile::PERFORMANCE_COMPONENT_PROFILE_ID;
pub use profile::PERFORMANCE_NON_CLAIMS;
pub use profile::PERFORMANCE_PROFILE_ID;
pub use profile::PERFORMANCE_PROFILE_SCHEMA;
pub use profile::SIGHTGLASS_REVISION;
pub use profile::WASMTIME_COMPONENT_COHORT;
pub use profile::performance_profile_ref;
pub use profile::performance_suite_ref;
pub use profile::supported_performance_profile;
pub use profile::validate_performance_profile;
pub use runner::SightglassProcessInvocation;
pub use runner::SightglassProcessResult;
pub use runner::parse_sightglass_measurements;
pub use runner::run_sightglass_process;
pub use runner::sightglass_arguments;

#[cfg(test)]
mod tests;
