use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum DeliveryIssue {
    SchemaMismatch,
    InvalidManifest,
    InvalidPolicy,
    InvalidState,
    HostBindingMismatch,
    HostNotRunning,
    InvalidIdentifier,
    InvalidReference,
    QueueMismatch,
    PolicyMismatch,
    GenerationMismatch,
    ConsistencyEpochMismatch,
    CurrentnessRequired,
    EngineEpochRequired,
    LogicalTimeRequired,
    LogicalTimeProfileMismatch,
    MissingAuthority,
    MissingPolicy,
    MissingResource,
    MissingEvidence,
    ConflictingDuplicateOperation,
    ItemAlreadyExists,
    ItemNotFound,
    QueueEmpty,
    NoEligibleItem,
    ReadyCapacityExceeded,
    InFlightCapacityExceeded,
    DeadLetterCapacityExceeded,
    MetadataLimitExceeded,
    TokenMismatch,
    WrongOwner,
    LeaseExpired,
    LeaseStillActive,
    AttemptLimitExceeded,
    FailureClassUnsupported,
    PoisonItemRetained,
    ExpiryAuthorityRequired,
    RedriveAuthorityRequired,
    RetentionAuthorityRequired,
    RetentionNotExpired,
    ArithmeticOverflow,
    WorkerAdmissionIncomplete,
}

impl DeliveryIssue {
    pub const fn code(&self) -> &'static str {
        match self {
            Self::SchemaMismatch => "delivery-schema-mismatch",
            Self::InvalidManifest => "delivery-invalid-manifest",
            Self::InvalidPolicy => "delivery-invalid-policy",
            Self::InvalidState => "delivery-invalid-state",
            Self::HostBindingMismatch => "delivery-host-binding-mismatch",
            Self::HostNotRunning => "delivery-host-not-running",
            Self::InvalidIdentifier => "delivery-invalid-identifier",
            Self::InvalidReference => "delivery-invalid-reference",
            Self::QueueMismatch => "delivery-queue-mismatch",
            Self::PolicyMismatch => "delivery-policy-mismatch",
            Self::GenerationMismatch => "delivery-generation-mismatch",
            Self::ConsistencyEpochMismatch => "delivery-consistency-epoch-mismatch",
            Self::CurrentnessRequired => "delivery-currentness-required",
            Self::EngineEpochRequired => "delivery-engine-epoch-required",
            Self::LogicalTimeRequired => "delivery-logical-time-required",
            Self::LogicalTimeProfileMismatch => "delivery-time-profile-mismatch",
            Self::MissingAuthority => "delivery-authority-required",
            Self::MissingPolicy => "delivery-policy-required",
            Self::MissingResource => "delivery-resource-required",
            Self::MissingEvidence => "delivery-evidence-required",
            Self::ConflictingDuplicateOperation => "delivery-conflicting-operation-id",
            Self::ItemAlreadyExists => "delivery-item-already-exists",
            Self::ItemNotFound => "delivery-item-not-found",
            Self::QueueEmpty => "delivery-queue-empty",
            Self::NoEligibleItem => "delivery-no-eligible-item",
            Self::ReadyCapacityExceeded => "delivery-ready-capacity",
            Self::InFlightCapacityExceeded => "delivery-in-flight-capacity",
            Self::DeadLetterCapacityExceeded => "delivery-dead-letter-capacity",
            Self::MetadataLimitExceeded => "delivery-metadata-limit",
            Self::TokenMismatch => "delivery-token-mismatch",
            Self::WrongOwner => "delivery-owner-mismatch",
            Self::LeaseExpired => "delivery-lease-expired",
            Self::LeaseStillActive => "delivery-lease-still-active",
            Self::AttemptLimitExceeded => "delivery-attempt-limit",
            Self::FailureClassUnsupported => "delivery-failure-class-unsupported",
            Self::PoisonItemRetained => "delivery-poison-item-retained",
            Self::ExpiryAuthorityRequired => "delivery-expiry-authority-required",
            Self::RedriveAuthorityRequired => "delivery-redrive-authority-required",
            Self::RetentionAuthorityRequired => "delivery-retention-authority-required",
            Self::RetentionNotExpired => "delivery-retention-not-expired",
            Self::ArithmeticOverflow => "delivery-arithmetic-overflow",
            Self::WorkerAdmissionIncomplete => "delivery-worker-admission-incomplete",
        }
    }
}
