use super::*;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum WorldFaultIssue {
    SchemaMismatch(&'static str),
    InventoryVersionMismatch,
    InventoryRowCount {
        actual: usize,
        expected: usize,
    },
    MissingMutation(WorldMutationKind),
    DuplicateMutation(WorldMutationKind),
    UnknownProductMutation(String),
    ProductMutationMissing(String),
    InventoryContractMismatch(WorldMutationKind),
    MissingRequiredPhase {
        mutation: WorldMutationKind,
        phase: FaultPhase,
    },
    MissingRequiredFailureCase {
        mutation: WorldMutationKind,
        case: RequiredFailureCase,
    },
    WitnessSupportOverclaim,
    InvalidLimit(&'static str),
    BoundExceeded {
        field: &'static str,
        actual: usize,
        maximum: usize,
    },
    EmptyIdentifier(&'static str),
    MalformedReference {
        field: &'static str,
        value: String,
    },
    IdentityLengthOverflow(&'static str),
    DuplicateAdapter(String),
    AdapterOwnerMissing(WorldMutationOwner),
    DuplicateCase(String),
    CaseMutationMissing(WorldMutationKind),
    CaseAdapterMissing(String),
    CasePhaseNotRequired {
        mutation: WorldMutationKind,
        phase: FaultPhase,
    },
    CaseExpectedDecisionMismatch {
        case_id: String,
        expected: RecoveryClass,
        actual: RecoveryClass,
    },
    DuplicateSchedule(String),
    ScheduleMutationMismatch(WorldMutationKind),
    SchedulePositionGap {
        schedule_id: String,
        expected: u32,
        actual: u32,
    },
    ScheduleOperationMissing(String),
    ScheduleStepBoundExceeded {
        actual: usize,
        maximum: usize,
    },
    ScheduleNodeGenerationZero(String),
    ObservationMissing(String),
    DuplicateObservation(String),
    ObservationOperationMismatch(String),
    ObservationPhaseMismatch(String),
    OwnerDecisionMismatch {
        case_id: String,
        expected: RecoveryClass,
        actual: RecoveryClass,
    },
    SuccessWithoutDurableReadBack(String),
    UnsafeRetryAfterPossibleSubmit(String),
    MissingStateBecameSuccess(String),
    CorruptStateMisclassified(String),
    ContradictoryStateMisclassified(String),
    LocalRollbackDetectionOverclaim(String),
    UnsafeCleanupAuthority(String),
    ConcurrentObservationMissing(String),
    ConcurrentObservationUnexpected(String),
    ConcurrentBindingMismatch(String),
    MultipleLinearizations {
        schedule_id: String,
        generation: u64,
    },
    DuplicateEffectRelease {
        operation_id: String,
        count: u32,
    },
    UnsupportedRowDropped(String),
    ReceiptNonClaimMissing(WorldFaultNonClaim),
    EvidenceAuthorityOverclaim,
}
