use std::io::Cursor;

use openraft::declare_raft_types;
use serde::{Deserialize, Serialize};

pub type NodeId = u64;

declare_raft_types!(
    pub TypeConfig:
        D = Request,
        R = Response,
        NodeId = NodeId,
        Node = openraft::BasicNode,
        SnapshotData = Cursor<Vec<u8>>,
);

/// Client requests replicated through Raft.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Request {
    Set {
        key: String,
        value: String,
    },
    Delete {
        key: String,
    },
    Txn {
        operations: Vec<TxnOp>,
    },
    LeaseGrant {
        lease_id: u64,
        ttl_ms: u64,
        timestamp_ms: u64,
    },
    LeaseAttach {
        lease_id: u64,
        key: String,
    },
    LeaseKeepAlive {
        lease_id: u64,
        timestamp_ms: u64,
    },
    LeaseRevoke {
        lease_id: u64,
    },
    WatchRegister {
        watch_id: u64,
        key: String,
        prefix: bool,
    },
    WatchCancel {
        watch_id: u64,
    },
    WatchFetch {
        watch_id: u64,
    },
}

/// Responses generated by the state machine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Response {
    Set {
        previous: Option<String>,
    },
    Delete {
        previous: Option<String>,
    },
    Get {
        value: Option<String>,
    },
    Txn {
        committed: bool,
        results: Vec<TxnOpResult>,
    },
    LeaseGranted {
        lease: LeaseRecord,
    },
    LeaseAttached {
        lease: LeaseRecord,
    },
    LeaseKeepAlive {
        lease: Option<LeaseRecord>,
    },
    LeaseRevoked {
        lease_id: u64,
        released_keys: Vec<String>,
    },
    WatchRegistered {
        watch_id: u64,
    },
    WatchCanceled {
        watch_id: u64,
        existed: bool,
    },
    WatchEvents {
        watch_id: u64,
        events: Vec<WatchEvent>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TxnOp {
    Assert { key: String, equals: Option<String> },
    Set { key: String, value: String },
    Delete { key: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TxnOpResult {
    Assert {
        key: String,
        current: Option<String>,
        success: bool,
    },
    Set {
        key: String,
        previous: Option<String>,
    },
    Delete {
        key: String,
        previous: Option<String>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LeaseRecord {
    pub lease_id: u64,
    pub ttl_ms: u64,
    pub expires_at_ms: u64,
    pub keys: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WatchEvent {
    pub revision: u64,
    pub key: String,
    pub kind: WatchEventKind,
    pub value: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WatchEventKind {
    Put,
    Delete,
}
