#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Issue {
    InvalidManifest,
    MissingPort,
    MissingAuthority,
    InvalidReference,
    DuplicateContent,
    DuplicatePeer,
    DuplicateReplica,
    DuplicateOperation,
    ConflictingOperation,
    InvalidPolicy,
    InvalidResourceLimit,
    TooManyContents,
    TooManyPeers,
    TooManyActions,
    QueueExhausted,
    ByteBudgetExhausted,
    NoVerifiedSource,
    InsufficientPeers,
    InsufficientFaultDomains,
    StaleMembershipEpoch,
    StalePlacementEpoch,
    StaleGeneration,
    RepairExhausted,
    MissingRetentionPin,
    ActiveRetentionPin,
    MissingCleanupAuthority,
    ProtectedFormMismatch,
}

impl Issue {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::InvalidManifest => "invalid-manifest",
            Self::MissingPort => "missing-port",
            Self::MissingAuthority => "missing-authority",
            Self::InvalidReference => "invalid-reference",
            Self::DuplicateContent => "duplicate-content",
            Self::DuplicatePeer => "duplicate-peer",
            Self::DuplicateReplica => "duplicate-replica",
            Self::DuplicateOperation => "duplicate-operation",
            Self::ConflictingOperation => "conflicting-operation",
            Self::InvalidPolicy => "invalid-policy",
            Self::InvalidResourceLimit => "invalid-resource-limit",
            Self::TooManyContents => "too-many-contents",
            Self::TooManyPeers => "too-many-peers",
            Self::TooManyActions => "too-many-actions",
            Self::QueueExhausted => "queue-exhausted",
            Self::ByteBudgetExhausted => "byte-budget-exhausted",
            Self::NoVerifiedSource => "no-verified-source",
            Self::InsufficientPeers => "insufficient-peers",
            Self::InsufficientFaultDomains => "insufficient-fault-domains",
            Self::StaleMembershipEpoch => "stale-membership-epoch",
            Self::StalePlacementEpoch => "stale-placement-epoch",
            Self::StaleGeneration => "stale-generation",
            Self::RepairExhausted => "repair-exhausted",
            Self::MissingRetentionPin => "missing-retention-pin",
            Self::ActiveRetentionPin => "active-retention-pin",
            Self::MissingCleanupAuthority => "missing-cleanup-authority",
            Self::ProtectedFormMismatch => "protected-form-mismatch",
        }
    }
}
