include!("parts/dag/p000/body.rs");
include!("parts/dag/p001/body.rs");
include!("parts/dag/p002/body.rs");
include!("parts/dag/p003/body.rs");
include!("parts/dag/p004/body.rs");
include!("parts/dag/p005/body.rs");
include!("parts/dag/p006/body.rs");
include!("parts/dag/p007/body.rs");
include!("parts/dag/p008/body.rs");
include!("parts/dag/p009/body.rs");
include!("parts/dag/p010/body.rs");
include!("parts/dag/p011/body.rs");
include!("parts/dag/p012/body.rs");
include!("parts/dag/p013/body.rs");
include!("parts/dag/p014/body.rs");
include!("parts/dag/p015/body.rs");
include!("parts/dag/p016/body.rs");
include!("parts/dag/p017/body.rs");
include!("parts/dag/p018/body.rs");
include!("parts/dag/p019/body.rs");
include!("parts/dag/p020/body.rs");
include!("parts/dag/p021/body.rs");
include!("parts/dag/p022/body.rs");
include!("parts/dag/p023/body.rs");
include!("parts/dag/p024/body.rs");
include!("parts/dag/p025/body.rs");
include!("parts/dag/p026/body.rs");
include!("parts/dag/p027/body.rs");

#[cfg(test)]
mod tests {
    include!("parts/dag/tests/m000/p000/body.rs");
    include!("parts/dag/tests/m000/p001/body.rs");
    include!("parts/dag/tests/m000/p002/body.rs");
    include!("parts/dag/tests/m000/p003/body.rs");
    include!("parts/dag/tests/m000/p004/body.rs");
    include!("parts/dag/tests/m000/p005/body.rs");
    include!("parts/dag/tests/m000/p006/body.rs");
    include!("parts/dag/tests/m000/p007/body.rs");
    include!("parts/dag/tests/m000/p008/body.rs");
}
