use super::super::*;
use super::cases::expected_failure_cases;

#[allow(
    tigerstyle::function_length,
    reason = "one exhaustive match exposes every field of each closed mutation contract for review"
)]
pub(super) fn expected_contract(mutation: WorldMutationKind) -> WorldMutationContract {
    let required_phases = FaultPhase::ALL.to_vec();
    let required_cases = expected_failure_cases(mutation);
    match mutation {
        WorldMutationKind::Capture => contract(
            mutation,
            WorldMutationOwner::WorldCommit,
            OperationIdentityDomain::Capture,
            "complete-capture-inputs-and-absent-or-identical-commit",
            WorldMutationEffect::PublishImmutableCommit,
            LinearizationPoint::ImmutableObjectPublication,
            DurableRecordKind::CaptureReceipt,
            UncertainWindow::PublicationBeforeReceipt,
            ReconciliationEntry::CaptureReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Head => contract(
            mutation,
            WorldMutationOwner::WorldHead,
            OperationIdentityDomain::HeadTransition,
            "exact-head-and-generation-with-current-authority",
            WorldMutationEffect::CompareAndSwapHead,
            LinearizationPoint::HeadTransactionCommit,
            DurableRecordKind::HeadTransitionReceipt,
            UncertainWindow::CommitBeforeResponse,
            ReconciliationEntry::HeadReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Promotion => contract(
            mutation,
            WorldMutationOwner::WorldPromotion,
            OperationIdentityDomain::PromotionTransaction,
            "exact-head-generation-authority-and-complete-reservation-set",
            WorldMutationEffect::CommitHeadAndReservations,
            LinearizationPoint::PromotionTransactionCommit,
            DurableRecordKind::PromotionAndReservationSet,
            UncertainWindow::CommitBeforeResponse,
            ReconciliationEntry::PromotionReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Witness => contract(
            mutation,
            WorldMutationOwner::WorldHeadWitness,
            OperationIdentityDomain::WitnessFinalization,
            "independent-current-witness-observation",
            WorldMutationEffect::FinalizeIndependentWitness,
            LinearizationPoint::WitnessRecordCommit,
            DurableRecordKind::IndependentWitnessRecord,
            UncertainWindow::CommitBeforeResponse,
            ReconciliationEntry::WitnessReadBack,
            MutationSupport::UnsupportedIndependentWitness,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Outbox => contract(
            mutation,
            WorldMutationOwner::WorldPromotionOutbox,
            OperationIdentityDomain::EffectAttempt,
            "committed-reservation-and-durable-attempt-identity",
            WorldMutationEffect::RecordAndDispatchEffectAttempt,
            LinearizationPoint::AttemptRecordCommit,
            DurableRecordKind::EffectAttemptRecord,
            UncertainWindow::ExternalSubmitBeforeObservation,
            ReconciliationEntry::AttemptRecovery,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Replication => contract(
            mutation,
            WorldMutationOwner::WorldDistribution,
            OperationIdentityDomain::ReplicationUpdate,
            "verified-closure-and-current-replica-observation",
            WorldMutationEffect::PublishReplicaAvailability,
            LinearizationPoint::ReplicaAvailabilityCommit,
            DurableRecordKind::ReachabilityReceipt,
            UncertainWindow::ReachabilityBeforeReceipt,
            ReconciliationEntry::ReplicationReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Import => contract(
            mutation,
            WorldMutationOwner::WorldReplay,
            OperationIdentityDomain::CapsuleImport,
            "complete-verified-capsule-member-set",
            WorldMutationEffect::PublishCapsuleAvailability,
            LinearizationPoint::CapsuleAvailabilityCommit,
            DurableRecordKind::ReplayImportReceipt,
            UncertainWindow::StagingBeforeAvailability,
            ReconciliationEntry::ImportReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::Retention => contract(
            mutation,
            WorldMutationOwner::WorldRetention,
            OperationIdentityDomain::RetentionUpdate,
            "complete-reachability-and-authorized-retention-facts",
            WorldMutationEffect::PublishRetentionRoots,
            LinearizationPoint::RetentionRootCommit,
            DurableRecordKind::RetentionRootInventory,
            UncertainWindow::CommitBeforeResponse,
            ReconciliationEntry::RetentionReadBack,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
        WorldMutationKind::GarbageCollection => contract(
            mutation,
            WorldMutationOwner::WorldGarbageCollection,
            OperationIdentityDomain::GarbageCollectionPlan,
            "complete-current-reachability-retention-and-authority-facts",
            WorldMutationEffect::PublishGarbageCollectionPlan,
            LinearizationPoint::GarbageCollectionPlanCommit,
            DurableRecordKind::GarbageCollectionPlan,
            UncertainWindow::PlanBeforeReceipt,
            ReconciliationEntry::GarbageCollectionReplan,
            MutationSupport::Supported,
            required_phases,
            required_cases,
        ),
    }
}

#[allow(
    clippy::too_many_arguments,
    tigerstyle::too_many_parameters,
    reason = "the constructor keeps every required mutation-contract field explicit and ordered"
)]
fn contract(
    mutation: WorldMutationKind,
    owner: WorldMutationOwner,
    operation_domain: OperationIdentityDomain,
    expected_pre_state: &'static str,
    effect: WorldMutationEffect,
    linearization_point: LinearizationPoint,
    durable_record: DurableRecordKind,
    uncertain_window: UncertainWindow,
    reconciliation_entry: ReconciliationEntry,
    support: MutationSupport,
    required_phases: Vec<FaultPhase>,
    required_cases: Vec<RequiredFailureCase>,
) -> WorldMutationContract {
    WorldMutationContract {
        mutation,
        owner,
        operation_domain,
        expected_pre_state,
        effects: vec![effect],
        linearization_point,
        durable_record,
        uncertain_window,
        reconciliation_entry,
        required_phases,
        required_cases,
        support,
    }
}
