include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p000/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p001/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p002/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p003/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p004/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p005/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p006/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p007/body.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/deterministic/parts/replay/p008/body.rs"));
