# Dogfood NixOS VM test: build REAL Aspen Rust code through the CI pipeline.
#
# Pushes the actual `aspen-constants` crate (2,600+ lines, 11 source files,
# 413 compile-time assertions, 15 unit tests) to Forge as a cargo project.
# CI auto-triggers a 2-stage pipeline (cargo check → build+test), the
# NixBuildWorker compiles it with rustPlatform.buildRustPackage, and the
# test runs the resulting binary.
#
# This is the self-hosting proof: Aspen builds and tests its own code.
#
#   1. Create a Forge repo
#   2. Push the real aspen-constants crate + a thin main.rs wrapper
#   3. CI auto-triggers: stage 1 = cargo check, stage 2 = build + cargo test
#   4. NixBuildWorker runs `nix build` → cargo compiles the crate
#   5. Verify both stages succeed, then run the built binary
#
# Run:
#   nix build .#checks.x86_64-linux.ci-dogfood-self-build-test --impure --option sandbox false
{
  pkgs,
  aspenNodePackage,
  aspenCliPackage,
  aspenCliPlugins,
  kvPluginWasm,
  forgePluginWasm,
  gitRemoteAspenPackage,
  nixpkgsFlake,
}: let
  secretKey = "0000000000000006000000000000000600000000000000060000000000000006";
  cookie = "ci-self-build-test";

  # Path to the real aspen-constants source tree.
  aspenConstantsSrc = ../../crates/aspen-constants/src;

  # CI config: 2-stage pipeline with stage dependency — mirrors real .aspen/ci.ncl.
  ciConfig = pkgs.writeText "ci.ncl" ''
    {
      name = "aspen-constants-build",
      stages = [
        {
          name = "check",
          jobs = [
            {
              name = "cargo-check",
              type = 'nix,
              flake_url = ".",
              flake_attr = "checks.x86_64-linux.cargo-check",
              isolation = 'none,
              timeout_secs = 600,
            },
          ],
        },
        {
          name = "build",
          depends_on = ["check"],
          jobs = [
            {
              name = "build-and-test",
              type = 'nix,
              flake_url = ".",
              flake_attr = "packages.x86_64-linux.default",
              isolation = 'none,
              timeout_secs = 600,
            },
          ],
        },
      ],
    }
  '';

  # Nix flake with two outputs:
  #   checks.x86_64-linux.cargo-check  — fast `cargo check` type validation
  #   packages.x86_64-linux.default    — full build + cargo test
  #
  # Uses rustPlatform.buildRustPackage for proper cargo builds with vendoring.
  selfBuildFlake = pkgs.writeText "flake.nix" ''
    {
      description = "Aspen constants — self-build verification";
      inputs.nixpkgs.url = "nixpkgs";
      outputs = { nixpkgs, self, ... }:
        let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
        in {
          packages.x86_64-linux.default = pkgs.rustPlatform.buildRustPackage {
            pname = "aspen-constants";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            doCheck = true;
          };
          checks.x86_64-linux.cargo-check = pkgs.stdenv.mkDerivation {
            name = "aspen-constants-cargo-check";
            src = ./.;
            nativeBuildInputs = [ pkgs.cargo pkgs.rustc ];
            buildPhase = "export HOME=$(mktemp -d) && cargo check 2>&1";
            installPhase = "touch $out";
          };
        };
    }
  '';

  # Cargo.toml: real aspen-constants metadata + binary target for the wrapper.
  cargoToml = pkgs.writeText "Cargo.toml" ''
    [package]
    name = "aspen-constants"
    version = "0.1.0"
    edition = "2024"
    description = "Tiger Style resource limits and constants for Aspen distributed systems"

    [lib]
    name = "aspen_constants"
    path = "src/lib.rs"

    [[bin]]
    name = "aspen-constants-check"
    path = "src/main.rs"

    [features]
    default = []
    sql = []
  '';

  # Cargo.lock for a zero-dependency crate.
  cargoLock = pkgs.writeText "Cargo.lock" ''
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    version = 3

    [[package]]
    name = "aspen-constants"
    version = "0.1.0"
  '';

  # Thin binary wrapper that exercises the real library.
  selfBuildMain = pkgs.writeText "main.rs" ''
    use aspen_constants::{api, ci, coordination, network, raft};

    fn main() {
        println!("=== Aspen Constants Self-Build ===");
        println!(
            "{} v{}",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION")
        );
        println!();

        // KV limits
        println!("MAX_KEY_SIZE         = {} bytes", api::MAX_KEY_SIZE);
        println!("MAX_VALUE_SIZE       = {} bytes", api::MAX_VALUE_SIZE);
        println!("MAX_SCAN_RESULTS     = {}", api::MAX_SCAN_RESULTS);
        println!("DEFAULT_SCAN_LIMIT   = {}", api::DEFAULT_SCAN_LIMIT);

        // Network
        println!("MAX_PEERS            = {}", network::MAX_PEERS);
        println!("MAX_CONNECTIONS      = {}", network::MAX_CONCURRENT_CONNECTIONS);
        println!("CONNECT_TIMEOUT      = {}s", network::IROH_CONNECT_TIMEOUT_SECS);
        println!("READ_TIMEOUT         = {}s", network::IROH_READ_TIMEOUT_SECS);

        // Raft
        println!("MAX_BATCH_SIZE       = {}", raft::MAX_BATCH_SIZE);

        // Coordination
        println!("MAX_CAS_RETRIES      = {}", coordination::MAX_CAS_RETRIES);

        // CI
        println!("MAX_CI_VMS           = {}", ci::MAX_CI_VMS_PER_NODE);

        // Runtime assertions (complement the 413 compile-time assertions in assertions.rs)
        assert!(api::MAX_KEY_SIZE < api::MAX_VALUE_SIZE);
        assert!(api::DEFAULT_SCAN_LIMIT <= api::MAX_SCAN_RESULTS);
        assert!(raft::MAX_BATCH_SIZE > 0);
        assert!(
            network::IROH_CONNECT_TIMEOUT_SECS < network::IROH_READ_TIMEOUT_SECS
        );

        println!();
        println!("All compile-time and runtime assertions passed");
        println!("Built by Aspen CI");
    }
  '';

  # Bundle the complete source tree as a single derivation:
  # real aspen-constants source + main.rs wrapper + Cargo.toml + flake.
  selfBuildRepo = pkgs.runCommand "aspen-self-build-repo" {} ''
    mkdir -p $out/src $out/.aspen

    # Real aspen-constants source (11 files, 2600+ lines)
    cp ${aspenConstantsSrc}/lib.rs       $out/src/
    cp ${aspenConstantsSrc}/api.rs       $out/src/
    cp ${aspenConstantsSrc}/assertions.rs $out/src/
    cp ${aspenConstantsSrc}/ci.rs        $out/src/
    cp ${aspenConstantsSrc}/coordination.rs $out/src/
    cp ${aspenConstantsSrc}/directory.rs  $out/src/
    cp ${aspenConstantsSrc}/network.rs   $out/src/
    cp ${aspenConstantsSrc}/plugin.rs    $out/src/
    cp ${aspenConstantsSrc}/proxy.rs     $out/src/
    cp ${aspenConstantsSrc}/raft.rs      $out/src/
    cp ${aspenConstantsSrc}/wasm.rs      $out/src/

    # Binary wrapper
    cp ${selfBuildMain} $out/src/main.rs

    # Build files
    cp ${cargoToml}        $out/Cargo.toml
    cp ${cargoLock}        $out/Cargo.lock
    cp ${selfBuildFlake}   $out/flake.nix
    cp ${ciConfig}         $out/.aspen/ci.ncl
  '';

  pluginHelpers = import ./lib/wasm-plugins.nix {
    inherit pkgs aspenCliPlugins;
    plugins = [
      {
        name = "kv";
        wasm = kvPluginWasm;
      }
      {
        name = "forge";
        wasm = forgePluginWasm;
      }
    ];
  };
in
  pkgs.testers.nixosTest {
    name = "ci-dogfood-self-build";
    skipLint = true;
    skipTypeCheck = true;

    nodes.node1 = {
      imports = [
        ../../nix/modules/aspen-node.nix
        pluginHelpers.nixosConfig
      ];

      services.aspen.node = {
        enable = true;
        package = aspenNodePackage;
        nodeId = 1;
        inherit cookie;
        secretKey = secretKey;
        storageBackend = "redb";
        dataDir = "/var/lib/aspen";
        logLevel = "info";
        relayMode = "disabled";
        enableWorkers = true;
        enableCi = true;
        features = ["forge" "blob"];
      };

      environment.systemPackages = [
        aspenCliPackage
        gitRemoteAspenPackage
        pkgs.git
        pkgs.nix
      ];

      networking.firewall.enable = false;
      nix.settings.experimental-features = ["nix-command" "flakes"];
      nix.settings.sandbox = false;
      nix.registry.nixpkgs.flake = nixpkgsFlake;

      # The inner nix build downloads rustc + cargo + stdenv from
      # cache.nixos.org (~3GB). The default writableStoreUseTmpfs=true
      # caps the writable store overlay at ~50% of RAM (not enough).
      virtualisation.memorySize = 4096;
      virtualisation.cores = 2;
      virtualisation.diskSize = 20480;
      virtualisation.writableStoreUseTmpfs = false;
    };

    testScript = ''
      import json, time

      SELF_BUILD_REPO = "${selfBuildRepo}"

      def get_ticket():
          return node1.succeed("cat /var/lib/aspen/cluster-ticket.txt").strip()

      def cli(cmd, check=True):
          ticket = get_ticket()
          run = f"aspen-cli --ticket '{ticket}' --json {cmd} >/tmp/_cli.json 2>/tmp/_cli.err"
          if check:
              node1.succeed(run)
          else:
              node1.execute(run)
          raw = node1.succeed("cat /tmp/_cli.json")
          try:
              return json.loads(raw)
          except (json.JSONDecodeError, ValueError):
              return raw.strip()

      def cli_text(cmd):
          ticket = get_ticket()
          node1.succeed(f"aspen-cli --ticket '{ticket}' {cmd} >/tmp/_cli.txt 2>/dev/null")
          return node1.succeed("cat /tmp/_cli.txt")

      def plugin_cli(cmd, check=True):
          ticket = get_ticket()
          run = f"aspen-plugin-cli --ticket '{ticket}' --json {cmd} >/tmp/_pcli.json 2>/tmp/_pcli.err"
          if check:
              node1.succeed(run)
          else:
              node1.execute(run)
          raw = node1.succeed("cat /tmp/_pcli.json")
          try:
              return json.loads(raw)
          except (json.JSONDecodeError, ValueError):
              return raw.strip()

      def wait_for_pipeline(run_id, timeout=600):
          deadline = time.time() + timeout
          while time.time() < deadline:
              result = cli(f"ci status {run_id}", check=False)
              if isinstance(result, dict):
                  status = result.get("status")
                  node1.log(f"Pipeline {run_id}: status={status}")
                  if status in ("success", "failed", "cancelled"):
                      return result
              time.sleep(5)
          raise Exception(f"Pipeline {run_id} did not complete within {timeout}s")

      # ── boot ─────────────────────────────────────────────────────
      start_all()
      node1.wait_for_unit("aspen-node.service")
      node1.wait_for_file("/var/lib/aspen/cluster-ticket.txt", timeout=30)
      node1.wait_until_succeeds(
          "aspen-cli --ticket $(cat /var/lib/aspen/cluster-ticket.txt) cluster health",
          timeout=60,
      )
      cli_text("cluster init")
      time.sleep(2)

      # ── plugins ──────────────────────────────────────────────────
      with subtest("install WASM plugins"):
          for name, wasm, manifest in [
              ("kv", "/etc/aspen-plugins/kv-plugin.wasm", "/etc/aspen-plugins/kv-plugin.json"),
              ("forge", "/etc/aspen-plugins/forge-plugin.wasm", "/etc/aspen-plugins/forge-plugin.json"),
          ]:
              plugin_cli(f"plugin install {wasm} --manifest {manifest}")
          plugin_cli("plugin reload", check=False)
          time.sleep(8)

      # ── create forge repo ────────────────────────────────────────
      with subtest("create forge repo"):
          out = cli("git init aspen-constants")
          repo_id = out.get("id") or out.get("repo_id")
          assert repo_id, f"no repo_id: {out}"
          node1.log(f"Repo: {repo_id}")

      with subtest("ci watch"):
          result = cli(f"ci watch {repo_id}")
          assert isinstance(result, dict) and result.get("is_success"), f"ci watch failed: {result}"

      # ── push real aspen-constants to forge ───────────────────────
      with subtest("push aspen-constants crate to forge"):
          node1.succeed(
              f"cp -r --no-preserve=mode {SELF_BUILD_REPO} /tmp/self-build-repo && "
              "cd /tmp/self-build-repo && "
              "git init --initial-branch=main && "
              "git config user.email 'test@test' && "
              "git config user.name 'Test' && "
              "git add -A && "
              "git commit -m 'aspen-constants: tiger style resource bounds'"
          )
          ticket = get_ticket()
          node1.succeed(
              f"cd /tmp/self-build-repo && "
              f"git remote add aspen 'aspen://{ticket}/{repo_id}' && "
              f"RUST_LOG=warn git push aspen main 2>/tmp/push.err"
          )
          # Verify we pushed the real source
          file_count = node1.succeed(
              "find /tmp/self-build-repo/src -name '*.rs' | wc -l"
          ).strip()
          node1.log(f"Pushed {file_count} Rust source files to Forge")
          assert int(file_count) >= 12, f"Expected >=12 .rs files, got {file_count}"

      # ── wait for pipeline ────────────────────────────────────────
      with subtest("pipeline auto-triggers"):
          deadline = time.time() + 60
          run_id = None
          while time.time() < deadline:
              out = cli("ci list", check=False)
              if isinstance(out, dict):
                  runs = out.get("runs", [])
                  if runs:
                      run_id = runs[0].get("run_id")
                      break
              time.sleep(3)
          assert run_id, "No pipeline triggered within 60s"
          node1.log(f"Pipeline: {run_id}")

      with subtest("2-stage pipeline succeeds"):
          final = wait_for_pipeline(run_id, timeout=600)
          node1.log(f"Final: {json.dumps(final, indent=2)}")
          status = final.get("status")

          if status == "failed":
              for stage in final.get("stages", []):
                  for job in stage.get("jobs", []):
                      jid = job.get("id", "")
                      if job.get("status") == "failed" and jid:
                          ticket = get_ticket()
                          node1.execute(
                              f"aspen-cli --ticket '{ticket}' ci logs {run_id} {jid} "
                              f">/tmp/fail.log 2>/dev/null"
                          )
                          logs = node1.succeed("tail -80 /tmp/fail.log 2>/dev/null || echo 'no logs'")
                          node1.log(f"Job '{job.get('name')}' logs:\n{logs}")

          assert status == "success", f"Pipeline failed: {status}: {final}"

      # ── verify both stages ───────────────────────────────────────
      with subtest("both stages completed"):
          stages = final.get("stages", [])
          assert len(stages) == 2, f"Expected 2 stages, got {len(stages)}: {stages}"

          stage_names = [s["name"] for s in stages]
          assert "check" in stage_names, f"Missing 'check' stage: {stage_names}"
          assert "build" in stage_names, f"Missing 'build' stage: {stage_names}"

          for stage in stages:
              assert stage["status"] == "success", \
                  f"Stage '{stage['name']}' status={stage['status']}, expected success"

      # ── verify build logs ────────────────────────────────────────
      with subtest("ci logs captured"):
          all_jobs = []
          for stage in final.get("stages", []):
              for job in stage.get("jobs", []):
                  if job.get("id"):
                      all_jobs.append(job)

          assert len(all_jobs) == 2, f"Expected 2 jobs, got {len(all_jobs)}"
          for job in all_jobs:
              assert job["status"] == "success", \
                  f"Job '{job.get('name')}' not success: {job['status']}"

              ticket = get_ticket()
              node1.execute(
                  f"aspen-cli --ticket '{ticket}' ci logs {run_id} {job['id']} "
                  f">/tmp/job-{job['id']}.log 2>/dev/null"
              )
              log = node1.succeed(f"cat /tmp/job-{job['id']}.log 2>/dev/null || echo empty").strip()
              assert log, f"No log output for job '{job.get('name')}'"
              node1.log(f"Job '{job.get('name')}': {len(log)} bytes of logs")

      # ── run the CI-built binary ──────────────────────────────────
      with subtest("run CI-built binary"):
          build_job = [j for j in all_jobs if j.get("name") == "build-and-test"][0]
          job_data = cli(f"kv get __jobs:{build_job['id']}", check=False)

          output_path = None
          if isinstance(job_data, dict):
              value = job_data.get("value", "")
              try:
                  job_result = json.loads(value) if isinstance(value, str) else value
                  data = job_result.get("result", {}).get("Success", {}).get("data", {})
                  paths = data.get("output_paths", [])
                  if paths:
                      output_path = paths[0]
              except (json.JSONDecodeError, ValueError, AttributeError) as e:
                  node1.log(f"Failed to parse job result: {e}")

          assert output_path, f"No output_path in job result: {job_data}"
          node1.log(f"Nix output path: {output_path}")

          binary = f"{output_path}/bin/aspen-constants-check"
          node1.succeed(f"test -x {binary}")

          output = node1.succeed(f"{binary}")
          node1.log(f"Binary output:\n{output}")
          assert "aspen-constants v0.1.0" in output, \
              f"Missing crate identity in output: {output}"
          assert "All compile-time and runtime assertions passed" in output, \
              f"Assertions missing from output: {output}"
          assert "Built by Aspen CI" in output, \
              f"Build attribution missing: {output}"
          assert "MAX_KEY_SIZE" in output, \
              f"Constants missing from output: {output}"

      node1.log("SELF-BUILD PASSED: Forge -> CI -> cargo build+test -> run binary")
    '';
  }
