# Dogfood NixOS VM test: build REAL Aspen Rust code through the CI pipeline.
#
# Pushes the actual `aspen-constants` crate (2,600+ lines, 11 source files,
# 413 compile-time assertions, 15 unit tests) to Forge as a cargo project.
# CI auto-triggers a 2-stage pipeline (cargo check → build+test), the
# NixBuildWorker compiles it with rustPlatform.buildRustPackage, and the
# test runs the resulting binary.
#
# Verifies the full artifact storage pipeline:
#   - iroh-blobs: NAR archived and stored (BLAKE3 hash)
#   - nix binary cache: narinfo entry registered (queryable via `cache query`)
#   - SNIX: decomposed content-addressed storage (BlobService + DirectoryService + PathInfoService)
#
# This is the self-hosting proof: Aspen builds, tests, and stores its own code.
#
#   1. Create a Forge repo
#   2. Push the real aspen-constants crate + a thin main.rs wrapper
#   3. CI auto-triggers: stage 1 = cargo check, stage 2 = build + cargo test
#   4. NixBuildWorker runs `nix build` → cargo compiles the crate
#   5. Verify both stages succeed
#   6. Verify blob upload, cache registration, and SNIX decomposition
#   7. Run the built binary
#
# Run:
#   nix build .#checks.x86_64-linux.ci-dogfood-self-build-test --impure --option sandbox false
{
  pkgs,
  aspenNodePackage,
  aspenCliPackage,
  aspenCliPlugins,
  kvPluginWasm,
  forgePluginWasm,
  gitRemoteAspenPackage,
  nixpkgsFlake,
}: let
  secretKey = "0000000000000006000000000000000600000000000000060000000000000006";
  cookie = "ci-self-build-test";

  # Path to the real aspen-constants source tree.
  aspenConstantsSrc = ../../crates/aspen-constants/src;

  # CI config: 2-stage pipeline with stage dependency — mirrors real .aspen/ci.ncl.
  ciConfig = pkgs.writeText "ci.ncl" ''
    {
      name = "aspen-constants-build",
      stages = [
        {
          name = "check",
          jobs = [
            {
              name = "cargo-check",
              type = 'nix,
              flake_url = ".",
              flake_attr = "checks.x86_64-linux.cargo-check",
              isolation = 'none,
              timeout_secs = 600,
            },
          ],
        },
        {
          name = "build",
          depends_on = ["check"],
          jobs = [
            {
              name = "build-and-test",
              type = 'nix,
              flake_url = ".",
              flake_attr = "packages.x86_64-linux.default",
              isolation = 'none,
              timeout_secs = 600,
            },
          ],
        },
      ],
    }
  '';

  # Nix flake with two outputs:
  #   checks.x86_64-linux.cargo-check  — fast `cargo check` type validation
  #   packages.x86_64-linux.default    — full build + cargo test
  #
  # Uses rustPlatform.buildRustPackage for proper cargo builds with vendoring.
  selfBuildFlake = pkgs.writeText "flake.nix" ''
    {
      description = "Aspen constants — self-build verification";
      inputs.nixpkgs.url = "nixpkgs";
      outputs = { nixpkgs, self, ... }:
        let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
        in {
          packages.x86_64-linux.default = pkgs.rustPlatform.buildRustPackage {
            pname = "aspen-constants";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            doCheck = true;
          };
          checks.x86_64-linux.cargo-check = pkgs.stdenv.mkDerivation {
            name = "aspen-constants-cargo-check";
            src = ./.;
            nativeBuildInputs = [ pkgs.cargo pkgs.rustc ];
            buildPhase = "export HOME=$(mktemp -d) && cargo check 2>&1";
            installPhase = "touch $out";
          };
        };
    }
  '';

  # Cargo.toml: real aspen-constants metadata + binary target for the wrapper.
  cargoToml = pkgs.writeText "Cargo.toml" ''
    [package]
    name = "aspen-constants"
    version = "0.1.0"
    edition = "2024"
    description = "Tiger Style resource limits and constants for Aspen distributed systems"

    [lib]
    name = "aspen_constants"
    path = "src/lib.rs"

    [[bin]]
    name = "aspen-constants-check"
    path = "src/main.rs"

    [features]
    default = []
    sql = []
  '';

  # Cargo.lock for a zero-dependency crate.
  cargoLock = pkgs.writeText "Cargo.lock" ''
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    version = 3

    [[package]]
    name = "aspen-constants"
    version = "0.1.0"
  '';

  # Thin binary wrapper that exercises the real library.
  selfBuildMain = pkgs.writeText "main.rs" ''
    use aspen_constants::{api, ci, coordination, network, raft};

    fn main() {
        println!("=== Aspen Constants Self-Build ===");
        println!(
            "{} v{}",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION")
        );
        println!();

        // KV limits
        println!("MAX_KEY_SIZE         = {} bytes", api::MAX_KEY_SIZE);
        println!("MAX_VALUE_SIZE       = {} bytes", api::MAX_VALUE_SIZE);
        println!("MAX_SCAN_RESULTS     = {}", api::MAX_SCAN_RESULTS);
        println!("DEFAULT_SCAN_LIMIT   = {}", api::DEFAULT_SCAN_LIMIT);

        // Network
        println!("MAX_PEERS            = {}", network::MAX_PEERS);
        println!("MAX_CONNECTIONS      = {}", network::MAX_CONCURRENT_CONNECTIONS);
        println!("CONNECT_TIMEOUT      = {}s", network::IROH_CONNECT_TIMEOUT_SECS);
        println!("READ_TIMEOUT         = {}s", network::IROH_READ_TIMEOUT_SECS);

        // Raft
        println!("MAX_BATCH_SIZE       = {}", raft::MAX_BATCH_SIZE);

        // Coordination
        println!("MAX_CAS_RETRIES      = {}", coordination::MAX_CAS_RETRIES);

        // CI
        println!("MAX_CI_VMS           = {}", ci::MAX_CI_VMS_PER_NODE);

        // Runtime assertions (complement the 413 compile-time assertions in assertions.rs)
        assert!(api::MAX_KEY_SIZE < api::MAX_VALUE_SIZE);
        assert!(api::DEFAULT_SCAN_LIMIT <= api::MAX_SCAN_RESULTS);
        assert!(raft::MAX_BATCH_SIZE > 0);
        assert!(
            network::IROH_CONNECT_TIMEOUT_SECS < network::IROH_READ_TIMEOUT_SECS
        );

        println!();
        println!("All compile-time and runtime assertions passed");
        println!("Built by Aspen CI");
    }
  '';

  # Bundle the complete source tree as a single derivation:
  # real aspen-constants source + main.rs wrapper + Cargo.toml + flake.
  selfBuildRepo = pkgs.runCommand "aspen-self-build-repo" {} ''
    mkdir -p $out/src $out/.aspen

    # Real aspen-constants source (11 files, 2600+ lines)
    cp ${aspenConstantsSrc}/lib.rs       $out/src/
    cp ${aspenConstantsSrc}/api.rs       $out/src/
    cp ${aspenConstantsSrc}/assertions.rs $out/src/
    cp ${aspenConstantsSrc}/ci.rs        $out/src/
    cp ${aspenConstantsSrc}/coordination.rs $out/src/
    cp ${aspenConstantsSrc}/directory.rs  $out/src/
    cp ${aspenConstantsSrc}/network.rs   $out/src/
    cp ${aspenConstantsSrc}/plugin.rs    $out/src/
    cp ${aspenConstantsSrc}/proxy.rs     $out/src/
    cp ${aspenConstantsSrc}/raft.rs      $out/src/
    cp ${aspenConstantsSrc}/wasm.rs      $out/src/

    # Binary wrapper
    cp ${selfBuildMain} $out/src/main.rs

    # Build files
    cp ${cargoToml}        $out/Cargo.toml
    cp ${cargoLock}        $out/Cargo.lock
    cp ${selfBuildFlake}   $out/flake.nix
    cp ${ciConfig}         $out/.aspen/ci.ncl
  '';

  pluginHelpers = import ./lib/wasm-plugins.nix {
    inherit pkgs aspenCliPlugins;
    plugins = [
      {
        name = "kv";
        wasm = kvPluginWasm;
      }
      {
        name = "forge";
        wasm = forgePluginWasm;
      }
    ];
  };
in
  pkgs.testers.nixosTest {
    name = "ci-dogfood-self-build";
    skipLint = true;
    skipTypeCheck = true;

    nodes.node1 = {
      imports = [
        ../../nix/modules/aspen-node.nix
        pluginHelpers.nixosConfig
      ];

      services.aspen.node = {
        enable = true;
        package = aspenNodePackage;
        nodeId = 1;
        inherit cookie;
        secretKey = secretKey;
        storageBackend = "redb";
        dataDir = "/var/lib/aspen";
        logLevel = "info";
        relayMode = "disabled";
        enableWorkers = true;
        enableCi = true;
        enableSnix = true;
        features = ["forge" "blob"];
      };

      environment.systemPackages = [
        aspenCliPackage
        gitRemoteAspenPackage
        pkgs.git
        pkgs.nix
        pkgs.bubblewrap # Required for native snix-build sandbox
      ];

      # bubblewrap needs user namespaces for sandboxed builds.
      security.unprivilegedUsernsClone = true;

      networking.firewall.enable = false;
      nix.settings.experimental-features = ["nix-command" "flakes"];
      nix.settings.sandbox = false;
      nix.registry.nixpkgs.flake = nixpkgsFlake;

      # The inner nix build downloads rustc + cargo + stdenv from
      # cache.nixos.org (~3GB). The default writableStoreUseTmpfs=true
      # caps the writable store overlay at ~50% of RAM (not enough).
      virtualisation.memorySize = 4096;
      virtualisation.cores = 2;
      virtualisation.diskSize = 20480;
      virtualisation.writableStoreUseTmpfs = false;
    };

    testScript = ''
      import json, time

      SELF_BUILD_REPO = "${selfBuildRepo}"

      def get_ticket():
          return node1.succeed("cat /var/lib/aspen/cluster-ticket.txt").strip()

      def cli(cmd, check=True):
          ticket = get_ticket()
          run = f"aspen-cli --ticket '{ticket}' --json {cmd} >/tmp/_cli.json 2>/tmp/_cli.err"
          if check:
              node1.succeed(run)
          else:
              node1.execute(run)
          raw = node1.succeed("cat /tmp/_cli.json")
          try:
              return json.loads(raw)
          except (json.JSONDecodeError, ValueError):
              return raw.strip()

      def cli_text(cmd):
          ticket = get_ticket()
          node1.succeed(f"aspen-cli --ticket '{ticket}' {cmd} >/tmp/_cli.txt 2>/dev/null")
          return node1.succeed("cat /tmp/_cli.txt")

      def plugin_cli(cmd, check=True):
          ticket = get_ticket()
          run = f"aspen-plugin-cli --ticket '{ticket}' --json {cmd} >/tmp/_pcli.json 2>/tmp/_pcli.err"
          if check:
              node1.succeed(run)
          else:
              node1.execute(run)
          raw = node1.succeed("cat /tmp/_pcli.json")
          try:
              return json.loads(raw)
          except (json.JSONDecodeError, ValueError):
              return raw.strip()

      def stream_job_logs(run_id, job_id, job_name):
          """Stream logs for a job via ci logs --follow, saving to file."""
          ticket = get_ticket()
          node1.log(f"=== streaming logs: {job_name} ({job_id}) ===")
          node1.execute(
              f"aspen-cli --ticket '{ticket}' ci logs --follow {run_id} {job_id} "
              f">/tmp/job-{job_id}.log 2>/dev/null"
          )
          log_size = node1.succeed(f"wc -c < /tmp/job-{job_id}.log").strip()
          node1.log(f"=== end logs: {job_name} ({log_size} bytes) ===")

      def wait_for_pipeline(run_id, timeout=600):
          """Wait for pipeline by streaming job logs as they're assigned."""
          deadline = time.time() + timeout
          streamed_jobs = set()
          while time.time() < deadline:
              result = cli(f"ci status {run_id}", check=False)
              if not isinstance(result, dict):
                  time.sleep(3)
                  continue

              # Stream logs for newly assigned jobs
              for stage in result.get("stages", []):
                  for job in stage.get("jobs", []):
                      jid = job.get("id", "")
                      if jid and jid not in streamed_jobs:
                          streamed_jobs.add(jid)
                          stream_job_logs(run_id, jid, job.get("name", "unknown"))

              status = result.get("status")
              node1.log(f"Pipeline {run_id}: status={status}")
              if status in ("success", "failed", "cancelled"):
                  return result
              time.sleep(3)
          raise Exception(f"Pipeline {run_id} did not complete within {timeout}s")

      # ── boot ─────────────────────────────────────────────────────
      start_all()
      node1.wait_for_unit("aspen-node.service")
      node1.wait_for_file("/var/lib/aspen/cluster-ticket.txt", timeout=30)
      node1.wait_until_succeeds(
          "aspen-cli --ticket $(cat /var/lib/aspen/cluster-ticket.txt) cluster health",
          timeout=60,
      )
      cli_text("cluster init")
      time.sleep(2)

      # ── plugins ──────────────────────────────────────────────────
      with subtest("install WASM plugins"):
          for name, wasm, manifest in [
              ("kv", "/etc/aspen-plugins/kv-plugin.wasm", "/etc/aspen-plugins/kv-plugin.json"),
              ("forge", "/etc/aspen-plugins/forge-plugin.wasm", "/etc/aspen-plugins/forge-plugin.json"),
          ]:
              plugin_cli(f"plugin install {wasm} --manifest {manifest}")
          plugin_cli("plugin reload", check=False)
          time.sleep(8)

      # ── create forge repo ────────────────────────────────────────
      with subtest("create forge repo"):
          out = cli("git init aspen-constants")
          repo_id = out.get("id") or out.get("repo_id")
          assert repo_id, f"no repo_id: {out}"
          node1.log(f"Repo: {repo_id}")

      with subtest("ci watch"):
          result = cli(f"ci watch {repo_id}")
          assert isinstance(result, dict) and result.get("is_success"), f"ci watch failed: {result}"

      # ── push real aspen-constants to forge ───────────────────────
      with subtest("push aspen-constants crate to forge"):
          node1.succeed(
              f"cp -r --no-preserve=mode {SELF_BUILD_REPO} /tmp/self-build-repo && "
              "cd /tmp/self-build-repo && "
              "git init --initial-branch=main && "
              "git config user.email 'test@test' && "
              "git config user.name 'Test' && "
              "git add -A && "
              "git commit -m 'aspen-constants: tiger style resource bounds'"
          )
          ticket = get_ticket()
          node1.succeed(
              f"cd /tmp/self-build-repo && "
              f"git remote add aspen 'aspen://{ticket}/{repo_id}' && "
              f"RUST_LOG=warn git push aspen main 2>/tmp/push.err"
          )
          # Verify we pushed the real source
          file_count = node1.succeed(
              "find /tmp/self-build-repo/src -name '*.rs' | wc -l"
          ).strip()
          node1.log(f"Pushed {file_count} Rust source files to Forge")
          assert int(file_count) >= 12, f"Expected >=12 .rs files, got {file_count}"

      # ── wait for pipeline ────────────────────────────────────────
      with subtest("pipeline auto-triggers"):
          deadline = time.time() + 60
          run_id = None
          while time.time() < deadline:
              out = cli("ci list", check=False)
              if isinstance(out, dict):
                  runs = out.get("runs", [])
                  if runs:
                      run_id = runs[0].get("run_id")
                      break
              time.sleep(3)
          assert run_id, "No pipeline triggered within 60s"
          node1.log(f"Pipeline: {run_id}")

      with subtest("2-stage pipeline succeeds"):
          final = wait_for_pipeline(run_id, timeout=600)
          node1.log(f"Final: {json.dumps(final, indent=2)}")
          status = final.get("status")
          assert status == "success", f"Pipeline failed: {status}: {final}"

      # ── verify both stages ───────────────────────────────────────
      with subtest("both stages completed"):
          stages = final.get("stages", [])
          assert len(stages) == 2, f"Expected 2 stages, got {len(stages)}: {stages}"

          stage_names = [s["name"] for s in stages]
          assert "check" in stage_names, f"Missing 'check' stage: {stage_names}"
          assert "build" in stage_names, f"Missing 'build' stage: {stage_names}"

          for stage in stages:
              assert stage["status"] == "success", \
                  f"Stage '{stage['name']}' status={stage['status']}, expected success"

      # ── verify native build path used ─────────────────────────────
      with subtest("native build path used"):
          # Check node logs for bwrap execution (native snix-build path).
          bwrap_log = node1.succeed(
              "journalctl -u aspen-node --no-pager 2>/dev/null "
              "| grep -c 'starting local-store bwrap build' || echo 0"
          ).strip()
          bwrap_count = int(bwrap_log)
          node1.log(f"Native bwrap builds: {bwrap_count}")

          # Count subprocess fallbacks (nix build invocations).
          fallback_log = node1.succeed(
              "journalctl -u aspen-node --no-pager 2>/dev/null "
              "| grep -c 'falling back to nix build subprocess' || echo 0"
          ).strip()
          fallback_count = int(fallback_log)
          node1.log(f"Subprocess fallbacks: {fallback_count}")

          # At least the build-and-test job should use native bwrap.
          # Allow at most 1 fallback (the cargo-check job's eval may time out
          # on first nixpkgs fetch in the VM).
          assert bwrap_count >= 1, \
              f"Expected at least 1 native bwrap build, got {bwrap_count}"
          assert fallback_count <= 1, \
              f"Too many subprocess fallbacks ({fallback_count}), expected at most 1"

          # Check for output registration
          registration_log = node1.succeed(
              "journalctl -u aspen-node --no-pager 2>/dev/null "
              "| grep -c 'registered output' || echo 0"
          ).strip()
          node1.log(f"Output registrations: {registration_log.strip()}")

      # ── verify build logs ────────────────────────────────────────
      with subtest("ci logs captured"):
          all_jobs = []
          for stage in final.get("stages", []):
              for job in stage.get("jobs", []):
                  if job.get("id"):
                      all_jobs.append(job)

          assert len(all_jobs) == 2, f"Expected 2 jobs, got {len(all_jobs)}"
          for job in all_jobs:
              assert job["status"] == "success", \
                  f"Job '{job.get('name')}' not success: {job['status']}"
              # Logs already saved to /tmp/job-{id}.log by stream_job_logs during wait
              log = node1.succeed(f"cat /tmp/job-{job['id']}.log 2>/dev/null || echo empty").strip()
              assert log, f"No log output for job '{job.get('name')}'"
              node1.log(f"Job '{job.get('name')}': {len(log)} bytes of logs")

      # ── extract job results ─────────────────────────────────────
      with subtest("extract job results"):
          build_job = [j for j in all_jobs if j.get("name") == "build-and-test"][0]
          job_data = cli(f"kv get __jobs:{build_job['id']}", check=False)

          output_path = None
          job_result_data = None
          if isinstance(job_data, dict):
              value = job_data.get("value", "")
              try:
                  job_result = json.loads(value) if isinstance(value, str) else value
                  job_result_data = job_result.get("result", {}).get("Success", {}).get("data", {})
                  paths = job_result_data.get("output_paths", [])
                  if paths:
                      output_path = paths[0]
              except (json.JSONDecodeError, ValueError, AttributeError) as e:
                  node1.log(f"Failed to parse job result: {e}")

          assert output_path, f"No output_path in job result: {job_data}"
          node1.log(f"Nix output path: {output_path}")

      # ── verify blob upload ──────────────────────────────────────
      with subtest("build output uploaded to blobs"):
          uploaded = job_result_data.get("uploaded_store_paths", [])
          assert len(uploaded) >= 1, f"No uploaded store paths: {job_result_data}"

          build_upload = [u for u in uploaded if "aspen-constants-0.1.0" in u.get("store_path", "")]
          assert len(build_upload) == 1, f"Expected 1 build upload, got {len(build_upload)}: {uploaded}"

          blob_hash = build_upload[0].get("blob_hash")
          nar_size = build_upload[0].get("nar_size", 0)
          cache_registered = build_upload[0].get("cache_registered", False)

          assert blob_hash, f"No blob_hash in upload: {build_upload[0]}"
          assert nar_size > 0, f"NAR size is 0: {build_upload[0]}"
          assert cache_registered, f"Store path not registered in cache: {build_upload[0]}"

          node1.log(f"Blob upload: hash={blob_hash} nar_size={nar_size} cached={cache_registered}")

      # ── verify nix binary cache entry ────────────────────────────
      with subtest("build output in nix binary cache"):
          cache_result = cli(f"cache query {output_path}", check=False)
          node1.log(f"Cache query result: {json.dumps(cache_result, indent=2)}")

          assert isinstance(cache_result, dict), f"Cache query failed: {cache_result}"
          assert cache_result.get("was_found"), f"Store path not found in cache: {cache_result}"
          assert cache_result.get("blob_hash") == blob_hash, \
              f"Blob hash mismatch: cache={cache_result.get('blob_hash')} upload={blob_hash}"
          assert cache_result.get("nar_size") == nar_size, \
              f"NAR size mismatch: cache={cache_result.get('nar_size')} upload={nar_size}"

          node1.log(f"Cache entry verified: {cache_result.get('store_path')}")

      # ── verify SNIX upload succeeded ─────────────────────────────
      with subtest("SNIX storage upload succeeded"):
          # Verify the snix feature compiled in: the key exists in job output.
          assert "uploaded_store_paths_snix" in job_result_data, \
              f"snix feature not compiled — missing uploaded_store_paths_snix: {job_result_data.keys()}"

          # Verify snix upload was attempted by checking node logs.
          snix_log = node1.succeed(
              "journalctl -u aspen-node --no-pager 2>/dev/null | grep -c 'Uploading store path to SNIX' || echo 0"
          ).strip()
          snix_attempts = int(snix_log)
          assert snix_attempts >= 1, \
              f"SNIX upload was never attempted (snix.is_enabled may be false): attempts={snix_attempts}"
          node1.log(f"SNIX upload attempts: {snix_attempts}")

          # Verify SNIX upload completed successfully.
          snix_uploads = job_result_data.get("uploaded_store_paths_snix", [])
          assert len(snix_uploads) >= 1, \
              f"No SNIX uploads completed: {job_result_data}"

          snix_build = [u for u in snix_uploads if "aspen-constants-0.1.0" in u.get("store_path", "")]
          assert len(snix_build) == 1, \
              f"Expected 1 SNIX upload for aspen-constants, got {len(snix_build)}: {snix_uploads}"

          snix_entry = snix_build[0]
          assert snix_entry.get("nar_size", 0) == nar_size, \
              f"SNIX/blob NAR size mismatch: snix={snix_entry.get('nar_size')} blob={nar_size}"
          assert snix_entry.get("nar_sha256"), \
              f"Missing nar_sha256 in SNIX upload: {snix_entry}"
          node1.log(f"SNIX upload verified: {snix_entry}")

      # ── verify cache stats ──────────────────────────────────────
      with subtest("cache stats reflect uploads"):
          stats = cli("cache stats", check=False)
          node1.log(f"Cache stats: {json.dumps(stats, indent=2)}")

          assert isinstance(stats, dict), f"Cache stats failed: {stats}"
          # Both jobs (cargo-check + build-and-test) upload their outputs
          assert stats.get("total_entries", 0) >= 2, \
              f"Expected >=2 cache entries (check + build), got {stats.get('total_entries')}"
          assert stats.get("total_nar_bytes", 0) > 0, \
              f"Total NAR bytes is 0: {stats}"

      # ── run the CI-built binary ──────────────────────────────────
      with subtest("run CI-built binary"):
          # The output_path comes from the job result. With native builds,
          # the output may be registered at the derivation output path
          # (via register_output_in_store) or at a content-addressed path.
          # Try the primary path first, then look for the binary in /nix/store
          # with a glob if the daemon-registered path differs.
          binary = f"{output_path}/bin/aspen-constants-check"
          binary_exists = node1.execute(f"test -x {binary}")[0] == 0

          if not binary_exists:
              # Native build may have registered output at a different path.
              # Search for the binary in /nix/store.
              node1.log(f"Binary not at {binary}, searching /nix/store...")
              found = node1.succeed(
                  "find /nix/store -maxdepth 2 -name aspen-constants-check -type f 2>/dev/null "
                  "| head -1"
              ).strip()
              assert found, \
                  f"Binary not found at {binary} or anywhere in /nix/store"
              binary = found
              node1.log(f"Found binary at alternate path: {binary}")

          output = node1.succeed(f"{binary}")
          node1.log(f"Binary output:\n{output}")
          assert "aspen-constants v0.1.0" in output, \
              f"Missing crate identity in output: {output}"
          assert "All compile-time and runtime assertions passed" in output, \
              f"Assertions missing from output: {output}"
          assert "Built by Aspen CI" in output, \
              f"Build attribution missing: {output}"
          assert "MAX_KEY_SIZE" in output, \
              f"Constants missing from output: {output}"

      node1.log("SELF-BUILD PASSED: Forge -> CI -> cargo build+test -> blob+cache+snix -> run binary")
    '';
  }
