# NixOS VM integration test for Federated CI Dogfood.
#
# Two-cluster test proving the full cross-cluster pipeline:
#   Alice creates a Forge repo, pushes a Nix flake, federates it.
#   Bob trusts Alice, syncs the federated repo, triggers a CI build
#   from the mirrored content, and runs the resulting binary.
#
# This combines federation (cross-cluster sync) with CI (nix build)
# to prove the complete self-hosted pipeline works across clusters.
#
# Run:
#   nix build .#checks.x86_64-linux.federation-ci-dogfood-test --impure --option sandbox false
{
  pkgs,
  aspenNodePackage,
  aspenCliPackage,
  aspenCliPlugins,
  kvPluginWasm,
  forgePluginWasm,
  gitRemoteAspenPackage,
  nixpkgsFlake,
}: let
  aliceSecretKey = "a11ce00000000007a11ce00000000007a11ce00000000007a11ce00000000007";
  bobSecretKey = "b0b0000000000008b0b0000000000008b0b0000000000008b0b0000000000008";

  aliceCookie = "alice-ci-dogfood";
  bobCookie = "bob-ci-dogfood";

  pluginHelpers = import ./lib/wasm-plugins.nix {
    inherit pkgs aspenCliPlugins;
    plugins = [
      {
        name = "kv";
        wasm = kvPluginWasm;
      }
      {
        name = "forge";
        wasm = forgePluginWasm;
      }
    ];
  };

  # Simple CI config: one shell job (echo) to verify pipeline triggers.
  # For the nix build, Bob will use `ci trigger` with a nix job.
  ciConfig = pkgs.writeText "ci.ncl" ''
    {
      name = "fed-dogfood",
      stages = [
        {
          name = "build",
          jobs = [
            {
              name = "nix-build",
              type = 'nix,
              flake_url = ".",
              flake_attr = "packages.x86_64-linux.default",
              isolation = 'none,
              timeout_secs = 600,
            },
          ],
        },
      ],
    }
  '';

  # Minimal Nix flake that builds a trivial binary.
  selfBuildFlake = pkgs.writeText "flake.nix" ''
    {
      description = "Federated CI dogfood test crate";
      inputs.nixpkgs.url = "nixpkgs";
      outputs = { nixpkgs, self, ... }:
        let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
        in {
          packages.x86_64-linux.default = pkgs.rustPlatform.buildRustPackage {
            pname = "fed-dogfood";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
          };
        };
    }
  '';

  cargoToml = pkgs.writeText "Cargo.toml" ''
    [package]
    name = "fed-dogfood"
    version = "0.1.0"
    edition = "2024"

    [[bin]]
    name = "fed-dogfood"
    path = "src/main.rs"
  '';

  cargoLock = pkgs.writeText "Cargo.lock" ''
    # This file is automatically @generated by Cargo.
    version = 3

    [[package]]
    name = "fed-dogfood"
    version = "0.1.0"
  '';

  mainRs = pkgs.writeText "main.rs" ''
    fn main() {
        println!("fed-dogfood v{}", env!("CARGO_PKG_VERSION"));
        println!("Built by federated CI pipeline");
        println!("Cross-cluster build succeeded");
    }
  '';

  # Bundle the source tree.
  selfBuildRepo = pkgs.runCommand "fed-dogfood-repo" {} ''
    mkdir -p $out/src $out/.aspen
    cp ${mainRs} $out/src/main.rs
    cp ${cargoToml} $out/Cargo.toml
    cp ${cargoLock} $out/Cargo.lock
    cp ${selfBuildFlake} $out/flake.nix
    cp ${ciConfig} $out/.aspen/ci.ncl
  '';

  mkClusterNode = {
    nodeId,
    secretKey,
    cookie,
    federationClusterKey,
    federationClusterName,
    enableCi ? false,
    extraPackages ? [],
  }: {
    imports = [
      ../../nix/modules/aspen-node.nix
      pluginHelpers.nixosConfig
    ];

    services.aspen.node = {
      enable = true;
      package = aspenNodePackage;
      inherit nodeId cookie secretKey;
      storageBackend = "redb";
      dataDir = "/var/lib/aspen";
      logLevel = "info";
      relayMode = "disabled";
      enableWorkers = enableCi;
      inherit enableCi;
      enableSnix = false;
      features = ["forge" "blob" "federation"];

      enableFederation = true;
      inherit federationClusterKey federationClusterName;
    };

    environment.systemPackages =
      [aspenCliPackage pkgs.git]
      ++ extraPackages;

    networking.firewall.enable = false;

    virtualisation.memorySize = 4096;
    virtualisation.cores = 2;
    virtualisation.diskSize = 20480;
    virtualisation.writableStoreUseTmpfs = false;

    nix.settings.experimental-features = ["nix-command" "flakes"];
    nix.settings.sandbox = false;
    nix.registry.nixpkgs.flake = nixpkgsFlake;
  };
in
  pkgs.testers.nixosTest {
    name = "federation-ci-dogfood";
    skipLint = true;
    skipTypeCheck = true;

    nodes = {
      alice = mkClusterNode {
        nodeId = 1;
        secretKey = aliceSecretKey;
        cookie = aliceCookie;
        federationClusterKey = aliceSecretKey;
        federationClusterName = "alice-cluster";
        extraPackages = [gitRemoteAspenPackage];
      };

      bob = mkClusterNode {
        nodeId = 1;
        secretKey = bobSecretKey;
        cookie = bobCookie;
        federationClusterKey = bobSecretKey;
        federationClusterName = "bob-cluster";
        enableCi = true;
        extraPackages = [gitRemoteAspenPackage pkgs.nix];
      };
    };

    testScript = ''
      import json
      import time
      import re

      SELF_BUILD_REPO = "${selfBuildRepo}"

      # ── helpers ──────────────────────────────────────────────────────

      def get_ticket(node):
          return node.succeed("cat /var/lib/aspen/cluster-ticket.txt").strip()

      def cli(node, cmd, check=True):
          ticket = get_ticket(node)
          run = (
              f"aspen-cli --ticket '{ticket}' --json {cmd} "
              f">/tmp/_cli_out.json 2>/dev/null"
          )
          if check:
              node.succeed(run)
          else:
              node.execute(run)
          raw = node.succeed("cat /tmp/_cli_out.json")
          try:
              return json.loads(raw)
          except (json.JSONDecodeError, ValueError):
              node.log(f"cli() JSON parse failed, raw={raw!r}")
              return raw.strip()

      def cli_text(node, cmd):
          ticket = get_ticket(node)
          node.succeed(
              f"aspen-cli --ticket '{ticket}' {cmd} "
              f">/tmp/_cli_out.txt 2>/dev/null"
          )
          return node.succeed("cat /tmp/_cli_out.txt")

      def wait_for_cluster(node, timeout=60):
          node.wait_for_unit("aspen-node.service")
          node.wait_for_file("/var/lib/aspen/cluster-ticket.txt", timeout=30)
          ticket = get_ticket(node)
          node.wait_until_succeeds(
              f"aspen-cli --ticket '{ticket}' cluster health 2>/dev/null",
              timeout=timeout,
          )

      def install_plugins(node):
          ticket = get_ticket(node)
          for pname in ["kv", "forge"]:
              wasm_path = f"/etc/aspen-plugins/{pname}-plugin.wasm"
              manifest_path = f"/etc/aspen-plugins/{pname}-plugin.json"
              node.succeed(
                  f"aspen-plugin-cli --ticket '{ticket}' --json "
                  f"plugin install {wasm_path} --manifest {manifest_path} "
                  f">/tmp/_plugin_out.json 2>/dev/null"
              )
          node.execute(
              f"aspen-plugin-cli --ticket '{ticket}' --json "
              f"plugin reload >/tmp/_plugin_out.json 2>/dev/null"
          )
          time.sleep(5)

      def stream_job_logs(node, run_id, job_id, job_name):
          ticket = get_ticket(node)
          node.log(f"=== streaming logs: {job_name} ({job_id}) ===")
          node.execute(
              f"aspen-cli --ticket '{ticket}' ci logs --follow {run_id} {job_id} "
              f">/tmp/job-{job_id}.log 2>/dev/null"
          )
          log_size = node.succeed(f"wc -c < /tmp/job-{job_id}.log").strip()
          node.log(f"=== end logs: {job_name} ({log_size} bytes) ===")

      def wait_for_pipeline(node, run_id, timeout=600):
          deadline = time.time() + timeout
          streamed_jobs = set()
          while time.time() < deadline:
              result = cli(node, f"ci status {run_id}", check=False)
              if not isinstance(result, dict):
                  time.sleep(3)
                  continue

              for stage in result.get("stages", []):
                  for job in stage.get("jobs", []):
                      jid = job.get("id", "")
                      if jid and jid not in streamed_jobs:
                          streamed_jobs.add(jid)
                          stream_job_logs(node, run_id, jid, job.get("name", "unknown"))

              status = result.get("status")
              node.log(f"Pipeline {run_id}: status={status}")
              if status in ("success", "failed", "cancelled"):
                  return result
              time.sleep(3)
          raise Exception(f"Pipeline {run_id} did not complete within {timeout}s")

      # ── boot both clusters ───────────────────────────────────────────
      start_all()

      wait_for_cluster(alice)
      wait_for_cluster(bob)

      cli_text(alice, "cluster init")
      cli_text(bob, "cluster init")
      time.sleep(2)

      install_plugins(alice)
      install_plugins(bob)

      # ── alice: create repo, push flake, federate ─────────────────────

      with subtest("alice creates forge repo"):
          out = cli(alice, "git init fed-dogfood --description 'Federation CI test'")
          alice_repo_id = out.get("id") or out.get("repo_id", "")
          assert alice_repo_id, f"repo init failed: {out}"
          alice.log(f"Alice repo: {alice_repo_id}")

      with subtest("alice pushes nix flake to forge"):
          ticket = get_ticket(alice)
          alice.succeed(
              f"cp -r --no-preserve=mode {SELF_BUILD_REPO} /tmp/fed-repo && "
              "cd /tmp/fed-repo && "
              "git init --initial-branch=main && "
              "git config user.email 'alice@test' && "
              "git config user.name 'Alice' && "
              "git add -A && "
              "git commit -m 'fed-dogfood: nix flake for CI build'"
          )
          rc, output = alice.execute(
              f"cd /tmp/fed-repo && "
              f"git remote add aspen 'aspen://{ticket}/{alice_repo_id}' && "
              f"RUST_LOG=warn git push aspen main 2>&1"
          )
          alice.log(f"git push rc={rc} output={output}")
          assert rc == 0, f"git push failed: {output}"
          time.sleep(2)

      with subtest("alice federates repo"):
          fed_result = cli(alice, f"federation federate {alice_repo_id} --mode public", check=False)
          alice.log(f"Federate result: {fed_result}")
          assert isinstance(fed_result, dict) and fed_result.get("is_success"), \
              f"federate failed: {fed_result}"

      # ── extract alice's identity ─────────────────────────────────────

      alice_health = cli(alice, "cluster health")
      alice_node_id = alice_health.get("iroh_node_id")
      assert alice_node_id, f"iroh_node_id missing: {alice_health}"

      alice_journal = alice.succeed("journalctl -u aspen-node --no-pager -q")
      addr_match = re.search(r'192\.168\.1\.1:(\d+)', alice_journal)
      assert addr_match, "could not find Alice's address in journal"
      alice_addr = f"192.168.1.1:{addr_match.group(1)}"
      alice.log(f"Alice: node_id={alice_node_id} addr={alice_addr}")

      # ── bob: trust, sync, verify mirror ──────────────────────────────

      with subtest("bob trusts alice"):
          trust_result = cli_text(bob, f"federation trust {alice_node_id}")
          bob.log(f"Trust result: {trust_result}")

      with subtest("bob syncs federated repo"):
          bob_ticket = get_ticket(bob)
          sync_cmd = (
              f"ASPEN_ORIGIN_ADDR='{alice_addr}' "
              f"aspen-cli --ticket '{bob_ticket}' "
              f"federation sync {alice_node_id} 2>&1"
          )
          bob.log(f"Sync: {sync_cmd}")
          rc, output = bob.execute(sync_cmd)
          bob.log(f"Sync rc={rc} output={output}")
          # May need a retry if connection not yet established
          if rc != 0:
              bob.log("Sync failed, retrying after 5s...")
              time.sleep(5)
              rc, output = bob.execute(sync_cmd)
              bob.log(f"Retry sync rc={rc} output={output}")
          time.sleep(3)

      with subtest("bob verifies mirror metadata"):
          # Check for _fed:mirror: keys in KV
          mirror_keys = cli(bob, "kv scan --prefix _fed:mirror:", check=False)
          bob.log(f"Mirror keys: {mirror_keys}")
          # Mirror should have entries (either dict with entries or list)
          has_mirrors = False
          if isinstance(mirror_keys, dict):
              entries = mirror_keys.get("entries", mirror_keys.get("keys", []))
              has_mirrors = len(entries) > 0
          elif isinstance(mirror_keys, list):
              has_mirrors = len(mirror_keys) > 0
          bob.log(f"Has mirrors: {has_mirrors}")
          # Not blocking — mirror metadata format may vary

      # ── bob: trigger CI build on mirrored content ────────────────────

      with subtest("bob sets up CI watch"):
          # Bob needs a local repo to attach CI to.
          # Create a forge repo and configure CI watch.
          bob_repo_out = cli(bob, "git init fed-dogfood-mirror --description 'Mirror build'")
          bob_repo_id = bob_repo_out.get("id") or bob_repo_out.get("repo_id", "")
          assert bob_repo_id, f"bob repo init failed: {bob_repo_out}"
          bob.log(f"Bob repo: {bob_repo_id}")

          watch_result = cli(bob, f"ci watch {bob_repo_id}")
          assert isinstance(watch_result, dict) and watch_result.get("is_success"), \
              f"ci watch failed: {watch_result}"

      with subtest("bob pushes federated content to local repo"):
          # Clone from alice via federation, push to bob's local forge repo
          bob_ticket = get_ticket(bob)
          fed_url = f"aspen://{bob_ticket}/fed:{alice_node_id}:{alice_repo_id}"

          clone_cmd = (
              f"ASPEN_ORIGIN_ADDR='{alice_addr}' "
              f"git clone '{fed_url}' /tmp/bob-fed-clone 2>&1"
          )
          bob.log(f"Clone: {clone_cmd}")
          rc, output = bob.execute(clone_cmd)
          bob.log(f"Clone rc={rc} output={output}")
          if rc != 0:
              bob.log("Clone failed, retrying after 10s...")
              time.sleep(10)
              bob.execute("rm -rf /tmp/bob-fed-clone")
              rc, output = bob.execute(clone_cmd)
              bob.log(f"Retry clone rc={rc} output={output}")
          assert rc == 0, f"federated clone failed: {output}"

          # Push the cloned content to bob's local forge repo for CI
          bob.succeed(
              "cd /tmp/bob-fed-clone && "
              f"git remote add bob-forge 'aspen://{bob_ticket}/{bob_repo_id}' && "
              f"RUST_LOG=warn git push bob-forge main 2>&1"
          )
          time.sleep(2)

      with subtest("bob waits for CI pipeline"):
          deadline = time.time() + 60
          run_id = None
          while time.time() < deadline:
              out = cli(bob, "ci list", check=False)
              if isinstance(out, dict):
                  runs = out.get("runs", [])
                  if runs:
                      run_id = runs[0].get("run_id")
                      break
              time.sleep(3)
          assert run_id, "No pipeline triggered on Bob within 60s"
          bob.log(f"Bob pipeline: {run_id}")

      with subtest("bob pipeline succeeds"):
          final = wait_for_pipeline(bob, run_id, timeout=1200)
          bob.log(f"Final: {json.dumps(final, indent=2)}")
          status = final.get("status")
          assert status == "success", f"Pipeline failed: {status}: {final}"

      # ── verify build output ──────────────────────────────────────────

      with subtest("verify CI build produced runnable binary"):
          stages = final.get("stages", [])
          assert len(stages) >= 1, f"Expected at least 1 stage, got {len(stages)}"

          all_jobs = []
          for stage in stages:
              for job in stage.get("jobs", []):
                  if job.get("id"):
                      all_jobs.append(job)

          build_job = [j for j in all_jobs if j.get("name") == "nix-build"]
          assert len(build_job) == 1, f"Expected nix-build job: {all_jobs}"
          build_job = build_job[0]

          assert build_job["status"] == "success", \
              f"nix-build job not success: {build_job['status']}"

          # Extract output path from job result
          job_data = cli(bob, f"kv get __jobs:{build_job['id']}", check=False)
          output_path = None
          if isinstance(job_data, dict):
              value = job_data.get("value", "")
              try:
                  job_result = json.loads(value) if isinstance(value, str) else value
                  result_data = job_result.get("result", {}).get("Success", {}).get("data", {})
                  paths = result_data.get("output_paths", [])
                  if paths:
                      output_path = paths[0]
              except (json.JSONDecodeError, ValueError, AttributeError) as e:
                  bob.log(f"Failed to parse job result: {e}")

          assert output_path, f"No output_path in build job: {job_data}"
          bob.log(f"Nix output path: {output_path}")

      with subtest("run CI-built binary"):
          binary = f"{output_path}/bin/fed-dogfood"
          bob.succeed(f"test -x {binary}")

          output = bob.succeed(f"{binary}")
          bob.log(f"Binary output:\n{output}")
          assert "fed-dogfood v0.1.0" in output, \
              f"Missing version in output: {output}"
          assert "Built by federated CI pipeline" in output, \
              f"Missing build attribution: {output}"
          assert "Cross-cluster build succeeded" in output, \
              f"Missing success marker: {output}"

      alice.log("FEDERATION CI DOGFOOD PASSED")
      bob.log("FEDERATION CI DOGFOOD PASSED")
    '';
  }
