// Trace-only coverage anchors for multinode testing harness requirements.
//
// The implementation lives in `src/testing/multinode.rs`; Cairn Tracey currently
// scans `tools/` and `crates/` for requirement references.

// r[impl molten.testing.multinode.declarative_scenario_fixtures]
// r[verify molten.testing.multinode.declarative_scenario_fixtures]
// r[impl molten.testing.multinode.scenario_fixture_validation]
// r[verify molten.testing.multinode.scenario_fixture_validation]
// r[impl molten.testing.multinode.topology_profile_matrix]
// r[verify molten.testing.multinode.topology_profile_matrix]
// r[impl molten.testing.multinode.role_membership_negatives]
// r[verify molten.testing.multinode.role_membership_negatives]
// r[impl molten.testing.multinode.cross_node_reconciliation_gate]
// r[verify molten.testing.multinode.cross_node_reconciliation_gate]
// r[impl molten.testing.multinode.reconciliation_deny_drift]
// r[verify molten.testing.multinode.reconciliation_deny_drift]
// r[impl molten.testing.multinode.local_multiprocess_harness]
// r[verify molten.testing.multinode.local_multiprocess_harness]
// r[impl molten.testing.multinode.process_isolation_cleanup]
// r[verify molten.testing.multinode.process_isolation_cleanup]
// r[impl molten.testing.multinode.failure_repro_bundle]
// r[verify molten.testing.multinode.failure_repro_bundle]
// r[impl molten.testing.multinode.failure_repro_privacy_and_replay]
// r[verify molten.testing.multinode.failure_repro_privacy_and_replay]
// r[impl molten.testing.distributed_simulation.generated_fault_interleavings]
// r[verify molten.testing.distributed_simulation.generated_fault_interleavings]
// r[impl molten.testing.distributed_simulation.generated_repro_seed]
// r[verify molten.testing.distributed_simulation.generated_repro_seed]
// r[impl molten.testing.nixos_vm.cross_node_live_transport]
// r[verify molten.testing.nixos_vm.cross_node_live_transport]
// r[impl molten.testing.nixos_vm.live_transport_negative_gate]
// r[verify molten.testing.nixos_vm.live_transport_negative_gate]
// r[impl molten.testing.nixos_vm.executable_fault_support_matrix]
// r[verify molten.testing.nixos_vm.executable_fault_support_matrix]
// r[impl molten.testing.nixos_vm.executable_fault_validation_negatives]
// r[verify molten.testing.nixos_vm.executable_fault_validation_negatives]
