
fn insert_source_path_bounded(values: &mut std::collections::BTreeSet<String>, value: String) -> Result<()> {
    if !values.contains(&value) && values.len() >= MAX_SOURCE_INVENTORY_PATHS {
        return Err(MoltenError::invalid_harness("source inventory exceeds path bound"));
    }
    values.insert(value);
    Ok(())
}

fn surface_inventory_values(metrics: &RunMetrics) -> Vec<IoValue> {
    critical_surface_definitions()
        .iter()
        .map(|surface| surface_inventory_value(surface, metrics))
        .collect()
}

fn surface_inventory_value(surface: &SurfaceDefinition, metrics: &RunMetrics) -> IoValue {
    let mut by_lint = Map::new();
    let mut total = 0u64;
    for finding in &metrics.findings {
        if surface.files.iter().any(|path| *path == finding.file) {
            total = total.saturating_add(finding.count);
            increment_count(&mut by_lint, &finding.lint, finding.count);
        }
    }
    record("surface", vec![
        record("name", vec![string(surface.name)]),
        record("files", vec![sequence(surface.files.iter().map(string).collect())]),
        record("reason", vec![string(surface.reason)]),
        record("findings", vec![u64_value(total)]),
        record("critical-findings", vec![u64_value(critical_count(&by_lint))]),
        record("by-lint", vec![sequence(metric_values(&sorted_metric_entries(
            by_lint,
            MAX_METRIC_ROWS,
        )))]),
    ])
}

const SURFACES: &[SurfaceDefinition] = &[
    SurfaceDefinition {
        name: "source-gate-and-admission",
        files: &[
            "src/octet/gate.rs",
            "src/node/runtime.rs",
            "src/job/dag.rs",
            "src/upgrades/mod.rs",
        ],
        reason: "strict source-gate, startup, job admission, and upgrade evidence paths must fail closed",
    },
    SurfaceDefinition {
        name: "harness-and-gates",
        files: &[
            "src/harness/gate.rs",
            "src/harness/schema.rs",
            "src/harness/runner.rs",
            "src/nixos/vm.rs",
            "src/nixos/tests.rs",
        ],
        reason: "deterministic test evidence and gate receipts are release-blocking",
    },
    SurfaceDefinition {
        name: "node-runtime-startup",
        files: &["src/node/runtime.rs", "src/node/identity.rs", "src/resources/mod.rs"],
        reason: "node startup binds identity, resources, adapters, and source gates before side effects",
    },
    SurfaceDefinition {
        name: "job-execution",
        files: &[
            "src/job/dag.rs",
            "src/artifacts/mod.rs",
            "src/typed/storage.rs",
            "src/eval/cache.rs",
        ],
        reason: "local and remote job execution must preserve artifact and storage evidence",
    },
    SurfaceDefinition {
        name: "ledger-and-evidence",
        files: &["src/ledger/mod.rs", "src/evidence/mod.rs", "src/evidence/chain.rs"],
        reason: "ledger imports and chain receipts are the evidence substrate",
    },
    SurfaceDefinition {
        name: "adapter-boundaries",
        files: &[
            "src/harness/wasm/executor.rs",
            "src/harness/steel/executor.rs",
            "src/effects/mod.rs",
            "src/remote/dataspace.rs",
            "src/runtime/envelope/mod.rs",
            "src/runtime/envelope/tests.rs",
        ],
        reason: "executor and remote boundaries must deny ambient authority before side effects",
    },
    SurfaceDefinition {
        name: "redaction-and-export",
        files: &[
            "src/catalog/mod.rs",
            "src/catalog/mcp.rs",
            "src/transcripts/mod.rs",
            "src/harness/repro.rs",
        ],
        reason: "rendering and export paths must not leak confidential evidence",
    },
    SurfaceDefinition {
        name: "cli-artifact-output",
        files: &[
            "src/main.rs",
            "src/main/root.rs",
            "src/main/root/command.rs",
            "src/main/tests.rs",
            "src/main/tests/core/basic.rs",
            "src/main/tests/core/cache.rs",
            "src/main/tests/core/chunk.rs",
            "src/main/tests/core/protocol.rs",
            "src/main/tests/core/retention.rs",
            "src/main/tests/core/storage.rs",
            "src/main/tests/job/job.rs",
            "src/main/tests/job/job-admission.rs",
            "src/main/tests/job/job-run.rs",
            "src/main/tests/job/job-setup.rs",
            "src/main/tests/job/job-stale.rs",
            "src/main/tests/job/job-sync.rs",
            "src/main/tests/job/job-worker.rs",
            "src/main/tests/ops/catalog.rs",
            "src/main/tests/ops/helpers.rs",
            "src/main/tests/ops/misc.rs",
            "src/main/tests/ops/provenance.rs",
            "src/main/tests/ops/receipts.rs",
            "src/main/tests/ops/upgrade.rs",
            "src/cli/core/artifact.rs",
            "src/cli/core/artifact/command.rs",
            "src/cli/core/artifact/io.rs",
            "src/cli/core/artifact/ops.rs",
            "src/cli/core/cache.rs",
            "src/cli/core/cache/command.rs",
            "src/cli/core/catalog.rs",
            "src/cli/core/catalog/command.rs",
            "src/cli/core/catalog/filter.rs",
            "src/cli/core/catalog/io.rs",
            "src/cli/core/catalog/ops.rs",
            "src/cli/core/chunk.rs",
            "src/cli/core/chunk/command.rs",
            "src/cli/core/chunk/io.rs",
            "src/cli/core/chunk/ops.rs",
            "src/cli/workflow/coordination.rs",
            "src/cli/workflow/coordination/bounded.rs",
            "src/cli/workflow/coordination/command.rs",
            "src/cli/workflow/coordination/io.rs",
            "src/cli/workflow/coordination/ops.rs",
            "src/cli/workflow/delivery.rs",
            "src/cli/workflow/delivery/command.rs",
            "src/cli/workflow/delivery/io.rs",
            "src/cli/workflow/delivery/ops.rs",
            "src/cli/ops/dogfood.rs",
            "src/cli/ops/dogfood/archive.rs",
            "src/cli/ops/dogfood/command.rs",
            "src/cli/ops/dogfood/signed.rs",
            "src/cli/evidence/gate.rs",
            "src/cli/evidence/gate/command.rs",
            "src/cli/evidence/gate/io.rs",
            "src/cli/evidence/gate/ops.rs",
            "src/cli/evidence/receipts/command.rs",
            "src/cli/evidence/receipts/io.rs",
            "src/cli/evidence/receipts/keyring.rs",
            "src/cli/evidence/receipts/keys.rs",
            "src/cli/evidence/receipts/operator.rs",
            "src/cli/evidence/receipts/signing.rs",
            "src/cli/test/harness.rs",
            "src/cli/ops/node.rs",
            "src/cli/ops/node/authority.rs",
            "src/cli/ops/node/command.rs",
            "src/cli/ops/node/command/authority.rs",
            "src/cli/ops/node/command/base.rs",
            "src/cli/ops/node/command/control.rs",
            "src/cli/ops/node/command/health.rs",
            "src/cli/ops/node/command/live.rs",
            "src/cli/ops/node/control.rs",
            "src/cli/ops/node/control/ingress.rs",
            "src/cli/ops/node/core.rs",
            "src/cli/ops/node/health.rs",
            "src/cli/ops/node/lifecycle.rs",
            "src/cli/ops/node/workflow.rs",
            "src/cli/ops/node/workflow/ack.rs",
            "src/cli/ops/node/workflow/apply.rs",
            "src/cli/ops/node/workflow/bundle.rs",
            "src/cli/ops/node/workflow/gate.rs",
            "src/cli/ops/nixosvm.rs",
            "src/cli/ops/nixosvm/command.rs",
            "src/cli/ops/nixosvm/io.rs",
            "src/cli/ops/nixosvm/ops.rs",
            "src/cli/workflow/job.rs",
            "src/cli/workflow/job/command.rs",
            "src/cli/workflow/job/command/base.rs",
            "src/cli/workflow/job/command/refs.rs",
            "src/cli/workflow/job/command/sync.rs",
            "src/cli/workflow/job/command/worker.rs",
            "src/cli/workflow/job/core.rs",
            "src/cli/workflow/job/io.rs",
            "src/cli/workflow/job/refs.rs",
            "src/cli/workflow/job/schedule.rs",
            "src/cli/workflow/job/schedule/output.rs",
            "src/cli/workflow/job/schedule/phase.rs",
            "src/cli/workflow/job/sync.rs",
            "src/cli/workflow/job/sync/input.rs",
            "src/cli/workflow/job/worker.rs",
            "src/cli/ops/ledger.rs",
            "src/cli/ops/ledger/command.rs",
            "src/cli/ops/ledger/io.rs",
            "src/cli/ops/ledger/ops.rs",
            "src/cli/ops/octet.rs",
            "src/cli/ops/octet/baseline.rs",
            "src/cli/ops/octet/command.rs",
            "src/cli/ops/octet/io.rs",
            "src/cli/ops/octet/ops.rs",
            "src/cli/ops/plugin.rs",
            "src/cli/ops/prodsoak.rs",
            "src/cli/ops/prodsoak/command.rs",
            "src/cli/evidence/receipts.rs",
            "src/cli/runtime/raft.rs",
            "src/cli/runtime/raft/command.rs",
            "src/cli/runtime/raft/io.rs",
            "src/cli/runtime/raft/ops.rs",
            "src/cli/evidence/report.rs",
            "src/cli/evidence/report/command.rs",
            "src/cli/evidence/report/io.rs",
            "src/cli/evidence/report/ops.rs",
            "src/cli/workflow/protocol.rs",
            "src/cli/workflow/protocol/command.rs",
            "src/cli/workflow/protocol/io.rs",
            "src/cli/workflow/protocol/ops.rs",
            "src/cli/workflow/provenance.rs",
            "src/cli/workflow/provenance/command.rs",
            "src/cli/workflow/provenance/input.rs",
            "src/cli/workflow/provenance/io.rs",
            "src/cli/workflow/provenance/ops.rs",
            "src/cli/workflow/remote.rs",
            "src/cli/workflow/remote/command.rs",
            "src/cli/workflow/remote/io.rs",
            "src/cli/workflow/remote/ops.rs",
            "src/cli/test/replayfixture.rs",
            "src/cli/runtime/repro.rs",
            "src/cli/runtime/repro/bundle.rs",
            "src/cli/runtime/repro/command.rs",
            "src/cli/runtime/repro/io.rs",
            "src/cli/workflow/retention.rs",
            "src/cli/workflow/retention/clearance.rs",
            "src/cli/workflow/retention/command.rs",
            "src/cli/workflow/retention/command/base.rs",
            "src/cli/workflow/retention/command/live.rs",
            "src/cli/workflow/retention/command/ops.rs",
            "src/cli/workflow/retention/core.rs",
            "src/cli/workflow/retention/io.rs",
            "src/cli/workflow/retention/ops.rs",
            "src/cli/workflow/retention/send.rs",
            "src/cli/workflow/retention/workflow.rs",
            "src/cli/runtime/rewrite.rs",
            "src/cli/runtime/rewrite/command.rs",
            "src/cli/runtime/rewrite/input.rs",
            "src/cli/runtime/rewrite/io.rs",
            "src/cli/runtime/rewrite/ops.rs",
            "src/cli/core/schema.rs",
            "src/cli/core/schema/command.rs",
            "src/cli/core/schema/io.rs",
            "src/cli/core/schema/ops.rs",
            "src/cli/runtime/secrets.rs",
            "src/cli/runtime/service.rs",
            "src/cli/runtime/service/command.rs",
            "src/cli/runtime/service/io.rs",
            "src/cli/runtime/service/ops.rs",
            "src/cli/core/storage.rs",
            "src/cli/core/storage/command.rs",
            "src/cli/core/storage/io.rs",
            "src/cli/core/storage/ops.rs",
            "src/cli/core/transcript.rs",
            "src/cli/core/transcript/command.rs",
            "src/cli/core/transcript/io.rs",
            "src/cli/core/transcript/ops.rs",
            "src/cli/runtime/upgrade.rs",
            "src/cli/runtime/upgrade/command.rs",
            "src/cli/runtime/upgrade/io.rs",
            "src/cli/runtime/upgrade/ops.rs",
            "src/cli/runtime/vat.rs",
        ],
        reason: "the CLI is the imperative shell that materializes canonical artifacts",
    },
];

fn critical_surface_definitions() -> Vec<SurfaceDefinition> {
    SURFACES.to_vec()
}
