#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum ProllyIssue {
    ProfileSchemaMismatch,
    ProfileFieldMismatch(&'static str),
    ProfileBoundInvalid(&'static str),
    ProfileIdentityMismatch,
    IdentityFailure(String),
    MalformedReference(String),
    EntryLimitExceeded,
    EmptyKey,
    KeyLimitExceeded,
    ValueLimitExceeded,
    EntriesNotStrictlySorted,
    DuplicateKey,
    NodeSchemaMismatch,
    NodeProfileMismatch,
    NodeEncodingMalformed(&'static str),
    NodeEncodingTrailingBytes,
    NodeIdentityMismatch,
    NodeSizeMismatch,
    NodeSizeLimitExceeded,
    EmptyInternalNode,
    InternalFanoutExceeded,
    ChildRangeInvalid,
    ChildRangeOverlap,
    MissingBlock(String),
    DuplicateBlock(String),
    UnexpectedBlock(String),
    BlockBytesMismatch(String),
    TreeCycle(String),
    TreeHeightExceeded,
    RootSchemaMismatch,
    RootProfileMismatch,
    RootIdentityMismatch,
    RootEntryCountMismatch,
    EditInsertExisting(Vec<u8>),
    EditUpdateMissing(Vec<u8>),
    EditDeleteMissing(Vec<u8>),
    EditCountExceeded,
    DiffLimitExceeded,
    GraphLimitExceeded,
    DuplicateGraphFact(String),
    IncompleteGraph(String),
    BenchmarkOverclaim,
    DifferentialInputNotText,
}
