include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/fabric_transport/cross_process/iroh/parts/shell/p000/body.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/fabric_transport/cross_process/iroh/parts/shell/p001/body.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/fabric_transport/cross_process/iroh/parts/shell/p002/body.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/fabric_transport/cross_process/iroh/parts/shell/p003/body.rs"
));
